# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.cache/wt [current_project]
set_property parent.project_path C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files -quiet c:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files c:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet c:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.dcp
set_property used_in_implementation false [get_files c:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.dcp]
add_files -quiet c:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.dcp
set_property used_in_implementation false [get_files c:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/hdlsrc/noise_cancel_fixpt.v
  C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/noise_cancel_fixpt_wrapper.v
  C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/jtag_mac.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/mwfil_dpscram.vhd
  C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/mwfil_udfifo.vhd
  C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/mwfil_bus2dut.vhd
  C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/mwfil_controller.vhd
  C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/mwfil_dut2bus.vhd
  C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/jtag_mac_fifo_wrapper.vhd
  C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/simcycle_fifo_wrapper.vhd
  C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/mwfil_chifcore.vhd
  C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/mwfil_chiftop.vhd
  C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/noise_cancel_fixpt_fil.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/noise_cancel_fixpt_fil.xdc
set_property used_in_implementation false [get_files C:/Users/admin/Desktop/bhavesh/codegen/noise_cancel/fil/noise_cancel_fixpt_fil/filsrc/noise_cancel_fixpt_fil.xdc]


synth_design -top noise_cancel_fixpt_fil -part xc7a100tcsg324-1


write_checkpoint -force -noxdef noise_cancel_fixpt_fil.dcp

catch { report_utilization -file noise_cancel_fixpt_fil_utilization_synth.rpt -pb noise_cancel_fixpt_fil_utilization_synth.pb }
