# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/admin/Desktop/bhavesh/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.xci
# IP: The module: 'jtag_mac_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/bhavesh/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo/jtag_mac_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_mac_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/admin/Desktop/bhavesh/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo/jtag_mac_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_mac_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/admin/Desktop/bhavesh/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_mac_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/admin/Desktop/bhavesh/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.xci
# IP: The module: 'jtag_mac_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/bhavesh/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo/jtag_mac_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_mac_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/admin/Desktop/bhavesh/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo/jtag_mac_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_mac_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/admin/Desktop/bhavesh/noise_cancel/fil/noise_cancel_fixpt_fil/fpgaproj/noise_cancel_fixpt_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_mac_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
