// -------------------------------------------------------------
// 
// File Name: C:\Users\admin\Desktop\bhavesh\codegen\noise_cancel\hdlsrc\noise_cancel_fixpt.v
// Created: 2017-04-29 19:08:22
// 
// Generated by MATLAB 9.2, MATLAB Coder 3.3 and HDL Coder 3.10
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: noise_cancel_fixpt
// Source Path: noise_cancel_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module noise_cancel_fixpt
          (s_0,
           s_1,
           s_2,
           s_3,
           s_4,
           s_5,
           s_6,
           s_7,
           s_8,
           s_9,
           s_10,
           s_11,
           s_12,
           s_13,
           s_14,
           s_15,
           s_16,
           s_17,
           s_18,
           s_19,
           s_20,
           s_21,
           s_22,
           s_23,
           s_24,
           s_25,
           s_26,
           s_27,
           s_28,
           s_29,
           s_30,
           s_31,
           s_32,
           s_33,
           s_34,
           s_35,
           s_36,
           s_37,
           s_38,
           s_39,
           s_40,
           s_41,
           s_42,
           s_43,
           s_44,
           s_45,
           s_46,
           s_47,
           s_48,
           s_49,
           s_50,
           s_51,
           s_52,
           s_53,
           s_54,
           s_55,
           s_56,
           s_57,
           s_58,
           s_59,
           s_60,
           s_61,
           s_62,
           s_63,
           s_64,
           s_65,
           s_66,
           s_67,
           s_68,
           s_69,
           s_70,
           s_71,
           s_72,
           s_73,
           s_74,
           s_75,
           s_76,
           s_77,
           s_78,
           s_79,
           s_80,
           s_81,
           s_82,
           s_83,
           s_84,
           s_85,
           s_86,
           s_87,
           s_88,
           s_89,
           s_90,
           s_91,
           s_92,
           s_93,
           s_94,
           s_95,
           s_96,
           s_97,
           s_98,
           s_99,
           n_0,
           n_1,
           n_2,
           n_3,
           n_4,
           n_5,
           n_6,
           n_7,
           n_8,
           n_9,
           n_10,
           n_11,
           n_12,
           n_13,
           n_14,
           n_15,
           n_16,
           n_17,
           n_18,
           n_19,
           n_20,
           n_21,
           n_22,
           n_23,
           n_24,
           n_25,
           n_26,
           n_27,
           n_28,
           n_29,
           n_30,
           n_31,
           n_32,
           n_33,
           n_34,
           n_35,
           n_36,
           n_37,
           n_38,
           n_39,
           n_40,
           n_41,
           n_42,
           n_43,
           n_44,
           n_45,
           n_46,
           n_47,
           n_48,
           n_49,
           n_50,
           n_51,
           n_52,
           n_53,
           n_54,
           n_55,
           n_56,
           n_57,
           n_58,
           n_59,
           n_60,
           n_61,
           n_62,
           n_63,
           n_64,
           n_65,
           n_66,
           n_67,
           n_68,
           n_69,
           n_70,
           n_71,
           n_72,
           n_73,
           n_74,
           n_75,
           n_76,
           n_77,
           n_78,
           n_79,
           n_80,
           n_81,
           n_82,
           n_83,
           n_84,
           n_85,
           n_86,
           n_87,
           n_88,
           n_89,
           n_90,
           n_91,
           n_92,
           n_93,
           n_94,
           n_95,
           n_96,
           n_97,
           n_98,
           n_99,
           e_1_0,
           e_1_1,
           e_1_2,
           e_1_3,
           e_1_4,
           e_1_5,
           e_1_6,
           e_1_7,
           e_1_8,
           e_1_9,
           e_1_10,
           e_1_11,
           e_1_12,
           e_1_13,
           e_1_14,
           e_1_15,
           e_1_16,
           e_1_17,
           e_1_18,
           e_1_19,
           e_1_20,
           e_1_21,
           e_1_22,
           e_1_23,
           e_1_24,
           e_1_25,
           e_1_26,
           e_1_27,
           e_1_28,
           e_1_29,
           e_1_30,
           e_1_31,
           e_1_32,
           e_1_33,
           e_1_34,
           e_1_35,
           e_1_36,
           e_1_37,
           e_1_38,
           e_1_39,
           e_1_40,
           e_1_41,
           e_1_42,
           e_1_43,
           e_1_44,
           e_1_45,
           e_1_46,
           e_1_47,
           e_1_48,
           e_1_49,
           e_1_50,
           e_1_51,
           e_1_52,
           e_1_53,
           e_1_54,
           e_1_55,
           e_1_56,
           e_1_57,
           e_1_58,
           e_1_59,
           e_1_60,
           e_1_61,
           e_1_62,
           e_1_63,
           e_1_64,
           e_1_65,
           e_1_66,
           e_1_67,
           e_1_68,
           e_1_69,
           e_1_70,
           e_1_71,
           e_1_72,
           e_1_73,
           e_1_74,
           e_1_75,
           e_1_76,
           e_1_77,
           e_1_78,
           e_1_79,
           e_1_80,
           e_1_81,
           e_1_82,
           e_1_83,
           e_1_84,
           e_1_85,
           e_1_86,
           e_1_87,
           e_1_88,
           e_1_89,
           W_1,
           bhat_1_0,
           bhat_1_1,
           bhat_1_2,
           bhat_1_3,
           bhat_1_4,
           bhat_1_5,
           bhat_1_6,
           bhat_1_7,
           bhat_1_8,
           bhat_1_9,
           bhat_1_10,
           bhat_1_11,
           bhat_1_12,
           bhat_1_13,
           bhat_1_14,
           bhat_1_15,
           bhat_1_16,
           bhat_1_17,
           bhat_1_18,
           bhat_1_19,
           bhat_1_20,
           bhat_1_21,
           bhat_1_22,
           bhat_1_23,
           bhat_1_24,
           bhat_1_25,
           bhat_1_26,
           bhat_1_27,
           bhat_1_28,
           bhat_1_29,
           bhat_1_30,
           bhat_1_31,
           bhat_1_32,
           bhat_1_33,
           bhat_1_34,
           bhat_1_35,
           bhat_1_36,
           bhat_1_37,
           bhat_1_38,
           bhat_1_39,
           bhat_1_40,
           bhat_1_41,
           bhat_1_42,
           bhat_1_43,
           bhat_1_44,
           bhat_1_45,
           bhat_1_46,
           bhat_1_47,
           bhat_1_48,
           bhat_1_49,
           bhat_1_50,
           bhat_1_51,
           bhat_1_52,
           bhat_1_53,
           bhat_1_54,
           bhat_1_55,
           bhat_1_56,
           bhat_1_57,
           bhat_1_58,
           bhat_1_59,
           bhat_1_60,
           bhat_1_61,
           bhat_1_62,
           bhat_1_63,
           bhat_1_64,
           bhat_1_65,
           bhat_1_66,
           bhat_1_67,
           bhat_1_68,
           bhat_1_69,
           bhat_1_70,
           bhat_1_71,
           bhat_1_72,
           bhat_1_73,
           bhat_1_74,
           bhat_1_75,
           bhat_1_76,
           bhat_1_77,
           bhat_1_78,
           bhat_1_79,
           bhat_1_80,
           bhat_1_81,
           bhat_1_82,
           bhat_1_83,
           bhat_1_84,
           bhat_1_85,
           bhat_1_86,
           bhat_1_87,
           bhat_1_88,
           bhat_1_89,
           e_0,
           e_1,
           e_2,
           e_3,
           e_4,
           e_5,
           e_6,
           e_7,
           e_8,
           e_9,
           e_10,
           e_11,
           e_12,
           e_13,
           e_14,
           e_15,
           e_16,
           e_17,
           e_18,
           e_19,
           e_20,
           e_21,
           e_22,
           e_23,
           e_24,
           e_25,
           e_26,
           e_27,
           e_28,
           e_29,
           e_30,
           e_31,
           e_32,
           e_33,
           e_34,
           e_35,
           e_36,
           e_37,
           e_38,
           e_39,
           e_40,
           e_41,
           e_42,
           e_43,
           e_44,
           e_45,
           e_46,
           e_47,
           e_48,
           e_49,
           e_50,
           e_51,
           e_52,
           e_53,
           e_54,
           e_55,
           e_56,
           e_57,
           e_58,
           e_59,
           e_60,
           e_61,
           e_62,
           e_63,
           e_64,
           e_65,
           e_66,
           e_67,
           e_68,
           e_69,
           e_70,
           e_71,
           e_72,
           e_73,
           e_74,
           e_75,
           e_76,
           e_77,
           e_78,
           e_79,
           e_80,
           e_81,
           e_82,
           e_83,
           e_84,
           e_85,
           e_86,
           e_87,
           e_88,
           e_89,
           W,
           bhat_0,
           bhat_1,
           bhat_2,
           bhat_3,
           bhat_4,
           bhat_5,
           bhat_6,
           bhat_7,
           bhat_8,
           bhat_9,
           bhat_10,
           bhat_11,
           bhat_12,
           bhat_13,
           bhat_14,
           bhat_15,
           bhat_16,
           bhat_17,
           bhat_18,
           bhat_19,
           bhat_20,
           bhat_21,
           bhat_22,
           bhat_23,
           bhat_24,
           bhat_25,
           bhat_26,
           bhat_27,
           bhat_28,
           bhat_29,
           bhat_30,
           bhat_31,
           bhat_32,
           bhat_33,
           bhat_34,
           bhat_35,
           bhat_36,
           bhat_37,
           bhat_38,
           bhat_39,
           bhat_40,
           bhat_41,
           bhat_42,
           bhat_43,
           bhat_44,
           bhat_45,
           bhat_46,
           bhat_47,
           bhat_48,
           bhat_49,
           bhat_50,
           bhat_51,
           bhat_52,
           bhat_53,
           bhat_54,
           bhat_55,
           bhat_56,
           bhat_57,
           bhat_58,
           bhat_59,
           bhat_60,
           bhat_61,
           bhat_62,
           bhat_63,
           bhat_64,
           bhat_65,
           bhat_66,
           bhat_67,
           bhat_68,
           bhat_69,
           bhat_70,
           bhat_71,
           bhat_72,
           bhat_73,
           bhat_74,
           bhat_75,
           bhat_76,
           bhat_77,
           bhat_78,
           bhat_79,
           bhat_80,
           bhat_81,
           bhat_82,
           bhat_83,
           bhat_84,
           bhat_85,
           bhat_86,
           bhat_87,
           bhat_88,
           bhat_89);


  input   signed [13:0] s_0;  // sfix14_En17
  input   signed [13:0] s_1;  // sfix14_En17
  input   signed [13:0] s_2;  // sfix14_En17
  input   signed [13:0] s_3;  // sfix14_En17
  input   signed [13:0] s_4;  // sfix14_En17
  input   signed [13:0] s_5;  // sfix14_En17
  input   signed [13:0] s_6;  // sfix14_En17
  input   signed [13:0] s_7;  // sfix14_En17
  input   signed [13:0] s_8;  // sfix14_En17
  input   signed [13:0] s_9;  // sfix14_En17
  input   signed [13:0] s_10;  // sfix14_En17
  input   signed [13:0] s_11;  // sfix14_En17
  input   signed [13:0] s_12;  // sfix14_En17
  input   signed [13:0] s_13;  // sfix14_En17
  input   signed [13:0] s_14;  // sfix14_En17
  input   signed [13:0] s_15;  // sfix14_En17
  input   signed [13:0] s_16;  // sfix14_En17
  input   signed [13:0] s_17;  // sfix14_En17
  input   signed [13:0] s_18;  // sfix14_En17
  input   signed [13:0] s_19;  // sfix14_En17
  input   signed [13:0] s_20;  // sfix14_En17
  input   signed [13:0] s_21;  // sfix14_En17
  input   signed [13:0] s_22;  // sfix14_En17
  input   signed [13:0] s_23;  // sfix14_En17
  input   signed [13:0] s_24;  // sfix14_En17
  input   signed [13:0] s_25;  // sfix14_En17
  input   signed [13:0] s_26;  // sfix14_En17
  input   signed [13:0] s_27;  // sfix14_En17
  input   signed [13:0] s_28;  // sfix14_En17
  input   signed [13:0] s_29;  // sfix14_En17
  input   signed [13:0] s_30;  // sfix14_En17
  input   signed [13:0] s_31;  // sfix14_En17
  input   signed [13:0] s_32;  // sfix14_En17
  input   signed [13:0] s_33;  // sfix14_En17
  input   signed [13:0] s_34;  // sfix14_En17
  input   signed [13:0] s_35;  // sfix14_En17
  input   signed [13:0] s_36;  // sfix14_En17
  input   signed [13:0] s_37;  // sfix14_En17
  input   signed [13:0] s_38;  // sfix14_En17
  input   signed [13:0] s_39;  // sfix14_En17
  input   signed [13:0] s_40;  // sfix14_En17
  input   signed [13:0] s_41;  // sfix14_En17
  input   signed [13:0] s_42;  // sfix14_En17
  input   signed [13:0] s_43;  // sfix14_En17
  input   signed [13:0] s_44;  // sfix14_En17
  input   signed [13:0] s_45;  // sfix14_En17
  input   signed [13:0] s_46;  // sfix14_En17
  input   signed [13:0] s_47;  // sfix14_En17
  input   signed [13:0] s_48;  // sfix14_En17
  input   signed [13:0] s_49;  // sfix14_En17
  input   signed [13:0] s_50;  // sfix14_En17
  input   signed [13:0] s_51;  // sfix14_En17
  input   signed [13:0] s_52;  // sfix14_En17
  input   signed [13:0] s_53;  // sfix14_En17
  input   signed [13:0] s_54;  // sfix14_En17
  input   signed [13:0] s_55;  // sfix14_En17
  input   signed [13:0] s_56;  // sfix14_En17
  input   signed [13:0] s_57;  // sfix14_En17
  input   signed [13:0] s_58;  // sfix14_En17
  input   signed [13:0] s_59;  // sfix14_En17
  input   signed [13:0] s_60;  // sfix14_En17
  input   signed [13:0] s_61;  // sfix14_En17
  input   signed [13:0] s_62;  // sfix14_En17
  input   signed [13:0] s_63;  // sfix14_En17
  input   signed [13:0] s_64;  // sfix14_En17
  input   signed [13:0] s_65;  // sfix14_En17
  input   signed [13:0] s_66;  // sfix14_En17
  input   signed [13:0] s_67;  // sfix14_En17
  input   signed [13:0] s_68;  // sfix14_En17
  input   signed [13:0] s_69;  // sfix14_En17
  input   signed [13:0] s_70;  // sfix14_En17
  input   signed [13:0] s_71;  // sfix14_En17
  input   signed [13:0] s_72;  // sfix14_En17
  input   signed [13:0] s_73;  // sfix14_En17
  input   signed [13:0] s_74;  // sfix14_En17
  input   signed [13:0] s_75;  // sfix14_En17
  input   signed [13:0] s_76;  // sfix14_En17
  input   signed [13:0] s_77;  // sfix14_En17
  input   signed [13:0] s_78;  // sfix14_En17
  input   signed [13:0] s_79;  // sfix14_En17
  input   signed [13:0] s_80;  // sfix14_En17
  input   signed [13:0] s_81;  // sfix14_En17
  input   signed [13:0] s_82;  // sfix14_En17
  input   signed [13:0] s_83;  // sfix14_En17
  input   signed [13:0] s_84;  // sfix14_En17
  input   signed [13:0] s_85;  // sfix14_En17
  input   signed [13:0] s_86;  // sfix14_En17
  input   signed [13:0] s_87;  // sfix14_En17
  input   signed [13:0] s_88;  // sfix14_En17
  input   signed [13:0] s_89;  // sfix14_En17
  input   signed [13:0] s_90;  // sfix14_En17
  input   signed [13:0] s_91;  // sfix14_En17
  input   signed [13:0] s_92;  // sfix14_En17
  input   signed [13:0] s_93;  // sfix14_En17
  input   signed [13:0] s_94;  // sfix14_En17
  input   signed [13:0] s_95;  // sfix14_En17
  input   signed [13:0] s_96;  // sfix14_En17
  input   signed [13:0] s_97;  // sfix14_En17
  input   signed [13:0] s_98;  // sfix14_En17
  input   signed [13:0] s_99;  // sfix14_En17
  input   signed [13:0] n_0;  // sfix14_En15
  input   signed [13:0] n_1;  // sfix14_En15
  input   signed [13:0] n_2;  // sfix14_En15
  input   signed [13:0] n_3;  // sfix14_En15
  input   signed [13:0] n_4;  // sfix14_En15
  input   signed [13:0] n_5;  // sfix14_En15
  input   signed [13:0] n_6;  // sfix14_En15
  input   signed [13:0] n_7;  // sfix14_En15
  input   signed [13:0] n_8;  // sfix14_En15
  input   signed [13:0] n_9;  // sfix14_En15
  input   signed [13:0] n_10;  // sfix14_En15
  input   signed [13:0] n_11;  // sfix14_En15
  input   signed [13:0] n_12;  // sfix14_En15
  input   signed [13:0] n_13;  // sfix14_En15
  input   signed [13:0] n_14;  // sfix14_En15
  input   signed [13:0] n_15;  // sfix14_En15
  input   signed [13:0] n_16;  // sfix14_En15
  input   signed [13:0] n_17;  // sfix14_En15
  input   signed [13:0] n_18;  // sfix14_En15
  input   signed [13:0] n_19;  // sfix14_En15
  input   signed [13:0] n_20;  // sfix14_En15
  input   signed [13:0] n_21;  // sfix14_En15
  input   signed [13:0] n_22;  // sfix14_En15
  input   signed [13:0] n_23;  // sfix14_En15
  input   signed [13:0] n_24;  // sfix14_En15
  input   signed [13:0] n_25;  // sfix14_En15
  input   signed [13:0] n_26;  // sfix14_En15
  input   signed [13:0] n_27;  // sfix14_En15
  input   signed [13:0] n_28;  // sfix14_En15
  input   signed [13:0] n_29;  // sfix14_En15
  input   signed [13:0] n_30;  // sfix14_En15
  input   signed [13:0] n_31;  // sfix14_En15
  input   signed [13:0] n_32;  // sfix14_En15
  input   signed [13:0] n_33;  // sfix14_En15
  input   signed [13:0] n_34;  // sfix14_En15
  input   signed [13:0] n_35;  // sfix14_En15
  input   signed [13:0] n_36;  // sfix14_En15
  input   signed [13:0] n_37;  // sfix14_En15
  input   signed [13:0] n_38;  // sfix14_En15
  input   signed [13:0] n_39;  // sfix14_En15
  input   signed [13:0] n_40;  // sfix14_En15
  input   signed [13:0] n_41;  // sfix14_En15
  input   signed [13:0] n_42;  // sfix14_En15
  input   signed [13:0] n_43;  // sfix14_En15
  input   signed [13:0] n_44;  // sfix14_En15
  input   signed [13:0] n_45;  // sfix14_En15
  input   signed [13:0] n_46;  // sfix14_En15
  input   signed [13:0] n_47;  // sfix14_En15
  input   signed [13:0] n_48;  // sfix14_En15
  input   signed [13:0] n_49;  // sfix14_En15
  input   signed [13:0] n_50;  // sfix14_En15
  input   signed [13:0] n_51;  // sfix14_En15
  input   signed [13:0] n_52;  // sfix14_En15
  input   signed [13:0] n_53;  // sfix14_En15
  input   signed [13:0] n_54;  // sfix14_En15
  input   signed [13:0] n_55;  // sfix14_En15
  input   signed [13:0] n_56;  // sfix14_En15
  input   signed [13:0] n_57;  // sfix14_En15
  input   signed [13:0] n_58;  // sfix14_En15
  input   signed [13:0] n_59;  // sfix14_En15
  input   signed [13:0] n_60;  // sfix14_En15
  input   signed [13:0] n_61;  // sfix14_En15
  input   signed [13:0] n_62;  // sfix14_En15
  input   signed [13:0] n_63;  // sfix14_En15
  input   signed [13:0] n_64;  // sfix14_En15
  input   signed [13:0] n_65;  // sfix14_En15
  input   signed [13:0] n_66;  // sfix14_En15
  input   signed [13:0] n_67;  // sfix14_En15
  input   signed [13:0] n_68;  // sfix14_En15
  input   signed [13:0] n_69;  // sfix14_En15
  input   signed [13:0] n_70;  // sfix14_En15
  input   signed [13:0] n_71;  // sfix14_En15
  input   signed [13:0] n_72;  // sfix14_En15
  input   signed [13:0] n_73;  // sfix14_En15
  input   signed [13:0] n_74;  // sfix14_En15
  input   signed [13:0] n_75;  // sfix14_En15
  input   signed [13:0] n_76;  // sfix14_En15
  input   signed [13:0] n_77;  // sfix14_En15
  input   signed [13:0] n_78;  // sfix14_En15
  input   signed [13:0] n_79;  // sfix14_En15
  input   signed [13:0] n_80;  // sfix14_En15
  input   signed [13:0] n_81;  // sfix14_En15
  input   signed [13:0] n_82;  // sfix14_En15
  input   signed [13:0] n_83;  // sfix14_En15
  input   signed [13:0] n_84;  // sfix14_En15
  input   signed [13:0] n_85;  // sfix14_En15
  input   signed [13:0] n_86;  // sfix14_En15
  input   signed [13:0] n_87;  // sfix14_En15
  input   signed [13:0] n_88;  // sfix14_En15
  input   signed [13:0] n_89;  // sfix14_En15
  input   signed [13:0] n_90;  // sfix14_En15
  input   signed [13:0] n_91;  // sfix14_En15
  input   signed [13:0] n_92;  // sfix14_En15
  input   signed [13:0] n_93;  // sfix14_En15
  input   signed [13:0] n_94;  // sfix14_En15
  input   signed [13:0] n_95;  // sfix14_En15
  input   signed [13:0] n_96;  // sfix14_En15
  input   signed [13:0] n_97;  // sfix14_En15
  input   signed [13:0] n_98;  // sfix14_En15
  input   signed [13:0] n_99;  // sfix14_En15
  input   signed [13:0] e_1_0;  // sfix14_En17
  input   signed [13:0] e_1_1;  // sfix14_En17
  input   signed [13:0] e_1_2;  // sfix14_En17
  input   signed [13:0] e_1_3;  // sfix14_En17
  input   signed [13:0] e_1_4;  // sfix14_En17
  input   signed [13:0] e_1_5;  // sfix14_En17
  input   signed [13:0] e_1_6;  // sfix14_En17
  input   signed [13:0] e_1_7;  // sfix14_En17
  input   signed [13:0] e_1_8;  // sfix14_En17
  input   signed [13:0] e_1_9;  // sfix14_En17
  input   signed [13:0] e_1_10;  // sfix14_En17
  input   signed [13:0] e_1_11;  // sfix14_En17
  input   signed [13:0] e_1_12;  // sfix14_En17
  input   signed [13:0] e_1_13;  // sfix14_En17
  input   signed [13:0] e_1_14;  // sfix14_En17
  input   signed [13:0] e_1_15;  // sfix14_En17
  input   signed [13:0] e_1_16;  // sfix14_En17
  input   signed [13:0] e_1_17;  // sfix14_En17
  input   signed [13:0] e_1_18;  // sfix14_En17
  input   signed [13:0] e_1_19;  // sfix14_En17
  input   signed [13:0] e_1_20;  // sfix14_En17
  input   signed [13:0] e_1_21;  // sfix14_En17
  input   signed [13:0] e_1_22;  // sfix14_En17
  input   signed [13:0] e_1_23;  // sfix14_En17
  input   signed [13:0] e_1_24;  // sfix14_En17
  input   signed [13:0] e_1_25;  // sfix14_En17
  input   signed [13:0] e_1_26;  // sfix14_En17
  input   signed [13:0] e_1_27;  // sfix14_En17
  input   signed [13:0] e_1_28;  // sfix14_En17
  input   signed [13:0] e_1_29;  // sfix14_En17
  input   signed [13:0] e_1_30;  // sfix14_En17
  input   signed [13:0] e_1_31;  // sfix14_En17
  input   signed [13:0] e_1_32;  // sfix14_En17
  input   signed [13:0] e_1_33;  // sfix14_En17
  input   signed [13:0] e_1_34;  // sfix14_En17
  input   signed [13:0] e_1_35;  // sfix14_En17
  input   signed [13:0] e_1_36;  // sfix14_En17
  input   signed [13:0] e_1_37;  // sfix14_En17
  input   signed [13:0] e_1_38;  // sfix14_En17
  input   signed [13:0] e_1_39;  // sfix14_En17
  input   signed [13:0] e_1_40;  // sfix14_En17
  input   signed [13:0] e_1_41;  // sfix14_En17
  input   signed [13:0] e_1_42;  // sfix14_En17
  input   signed [13:0] e_1_43;  // sfix14_En17
  input   signed [13:0] e_1_44;  // sfix14_En17
  input   signed [13:0] e_1_45;  // sfix14_En17
  input   signed [13:0] e_1_46;  // sfix14_En17
  input   signed [13:0] e_1_47;  // sfix14_En17
  input   signed [13:0] e_1_48;  // sfix14_En17
  input   signed [13:0] e_1_49;  // sfix14_En17
  input   signed [13:0] e_1_50;  // sfix14_En17
  input   signed [13:0] e_1_51;  // sfix14_En17
  input   signed [13:0] e_1_52;  // sfix14_En17
  input   signed [13:0] e_1_53;  // sfix14_En17
  input   signed [13:0] e_1_54;  // sfix14_En17
  input   signed [13:0] e_1_55;  // sfix14_En17
  input   signed [13:0] e_1_56;  // sfix14_En17
  input   signed [13:0] e_1_57;  // sfix14_En17
  input   signed [13:0] e_1_58;  // sfix14_En17
  input   signed [13:0] e_1_59;  // sfix14_En17
  input   signed [13:0] e_1_60;  // sfix14_En17
  input   signed [13:0] e_1_61;  // sfix14_En17
  input   signed [13:0] e_1_62;  // sfix14_En17
  input   signed [13:0] e_1_63;  // sfix14_En17
  input   signed [13:0] e_1_64;  // sfix14_En17
  input   signed [13:0] e_1_65;  // sfix14_En17
  input   signed [13:0] e_1_66;  // sfix14_En17
  input   signed [13:0] e_1_67;  // sfix14_En17
  input   signed [13:0] e_1_68;  // sfix14_En17
  input   signed [13:0] e_1_69;  // sfix14_En17
  input   signed [13:0] e_1_70;  // sfix14_En17
  input   signed [13:0] e_1_71;  // sfix14_En17
  input   signed [13:0] e_1_72;  // sfix14_En17
  input   signed [13:0] e_1_73;  // sfix14_En17
  input   signed [13:0] e_1_74;  // sfix14_En17
  input   signed [13:0] e_1_75;  // sfix14_En17
  input   signed [13:0] e_1_76;  // sfix14_En17
  input   signed [13:0] e_1_77;  // sfix14_En17
  input   signed [13:0] e_1_78;  // sfix14_En17
  input   signed [13:0] e_1_79;  // sfix14_En17
  input   signed [13:0] e_1_80;  // sfix14_En17
  input   signed [13:0] e_1_81;  // sfix14_En17
  input   signed [13:0] e_1_82;  // sfix14_En17
  input   signed [13:0] e_1_83;  // sfix14_En17
  input   signed [13:0] e_1_84;  // sfix14_En17
  input   signed [13:0] e_1_85;  // sfix14_En17
  input   signed [13:0] e_1_86;  // sfix14_En17
  input   signed [13:0] e_1_87;  // sfix14_En17
  input   signed [13:0] e_1_88;  // sfix14_En17
  input   signed [13:0] e_1_89;  // sfix14_En17
  input   signed [13:0] W_1;  // sfix14_En15
  input   signed [13:0] bhat_1_0;  // sfix14_En17
  input   signed [13:0] bhat_1_1;  // sfix14_En17
  input   signed [13:0] bhat_1_2;  // sfix14_En17
  input   signed [13:0] bhat_1_3;  // sfix14_En17
  input   signed [13:0] bhat_1_4;  // sfix14_En17
  input   signed [13:0] bhat_1_5;  // sfix14_En17
  input   signed [13:0] bhat_1_6;  // sfix14_En17
  input   signed [13:0] bhat_1_7;  // sfix14_En17
  input   signed [13:0] bhat_1_8;  // sfix14_En17
  input   signed [13:0] bhat_1_9;  // sfix14_En17
  input   signed [13:0] bhat_1_10;  // sfix14_En17
  input   signed [13:0] bhat_1_11;  // sfix14_En17
  input   signed [13:0] bhat_1_12;  // sfix14_En17
  input   signed [13:0] bhat_1_13;  // sfix14_En17
  input   signed [13:0] bhat_1_14;  // sfix14_En17
  input   signed [13:0] bhat_1_15;  // sfix14_En17
  input   signed [13:0] bhat_1_16;  // sfix14_En17
  input   signed [13:0] bhat_1_17;  // sfix14_En17
  input   signed [13:0] bhat_1_18;  // sfix14_En17
  input   signed [13:0] bhat_1_19;  // sfix14_En17
  input   signed [13:0] bhat_1_20;  // sfix14_En17
  input   signed [13:0] bhat_1_21;  // sfix14_En17
  input   signed [13:0] bhat_1_22;  // sfix14_En17
  input   signed [13:0] bhat_1_23;  // sfix14_En17
  input   signed [13:0] bhat_1_24;  // sfix14_En17
  input   signed [13:0] bhat_1_25;  // sfix14_En17
  input   signed [13:0] bhat_1_26;  // sfix14_En17
  input   signed [13:0] bhat_1_27;  // sfix14_En17
  input   signed [13:0] bhat_1_28;  // sfix14_En17
  input   signed [13:0] bhat_1_29;  // sfix14_En17
  input   signed [13:0] bhat_1_30;  // sfix14_En17
  input   signed [13:0] bhat_1_31;  // sfix14_En17
  input   signed [13:0] bhat_1_32;  // sfix14_En17
  input   signed [13:0] bhat_1_33;  // sfix14_En17
  input   signed [13:0] bhat_1_34;  // sfix14_En17
  input   signed [13:0] bhat_1_35;  // sfix14_En17
  input   signed [13:0] bhat_1_36;  // sfix14_En17
  input   signed [13:0] bhat_1_37;  // sfix14_En17
  input   signed [13:0] bhat_1_38;  // sfix14_En17
  input   signed [13:0] bhat_1_39;  // sfix14_En17
  input   signed [13:0] bhat_1_40;  // sfix14_En17
  input   signed [13:0] bhat_1_41;  // sfix14_En17
  input   signed [13:0] bhat_1_42;  // sfix14_En17
  input   signed [13:0] bhat_1_43;  // sfix14_En17
  input   signed [13:0] bhat_1_44;  // sfix14_En17
  input   signed [13:0] bhat_1_45;  // sfix14_En17
  input   signed [13:0] bhat_1_46;  // sfix14_En17
  input   signed [13:0] bhat_1_47;  // sfix14_En17
  input   signed [13:0] bhat_1_48;  // sfix14_En17
  input   signed [13:0] bhat_1_49;  // sfix14_En17
  input   signed [13:0] bhat_1_50;  // sfix14_En17
  input   signed [13:0] bhat_1_51;  // sfix14_En17
  input   signed [13:0] bhat_1_52;  // sfix14_En17
  input   signed [13:0] bhat_1_53;  // sfix14_En17
  input   signed [13:0] bhat_1_54;  // sfix14_En17
  input   signed [13:0] bhat_1_55;  // sfix14_En17
  input   signed [13:0] bhat_1_56;  // sfix14_En17
  input   signed [13:0] bhat_1_57;  // sfix14_En17
  input   signed [13:0] bhat_1_58;  // sfix14_En17
  input   signed [13:0] bhat_1_59;  // sfix14_En17
  input   signed [13:0] bhat_1_60;  // sfix14_En17
  input   signed [13:0] bhat_1_61;  // sfix14_En17
  input   signed [13:0] bhat_1_62;  // sfix14_En17
  input   signed [13:0] bhat_1_63;  // sfix14_En17
  input   signed [13:0] bhat_1_64;  // sfix14_En17
  input   signed [13:0] bhat_1_65;  // sfix14_En17
  input   signed [13:0] bhat_1_66;  // sfix14_En17
  input   signed [13:0] bhat_1_67;  // sfix14_En17
  input   signed [13:0] bhat_1_68;  // sfix14_En17
  input   signed [13:0] bhat_1_69;  // sfix14_En17
  input   signed [13:0] bhat_1_70;  // sfix14_En17
  input   signed [13:0] bhat_1_71;  // sfix14_En17
  input   signed [13:0] bhat_1_72;  // sfix14_En17
  input   signed [13:0] bhat_1_73;  // sfix14_En17
  input   signed [13:0] bhat_1_74;  // sfix14_En17
  input   signed [13:0] bhat_1_75;  // sfix14_En17
  input   signed [13:0] bhat_1_76;  // sfix14_En17
  input   signed [13:0] bhat_1_77;  // sfix14_En17
  input   signed [13:0] bhat_1_78;  // sfix14_En17
  input   signed [13:0] bhat_1_79;  // sfix14_En17
  input   signed [13:0] bhat_1_80;  // sfix14_En17
  input   signed [13:0] bhat_1_81;  // sfix14_En17
  input   signed [13:0] bhat_1_82;  // sfix14_En17
  input   signed [13:0] bhat_1_83;  // sfix14_En17
  input   signed [13:0] bhat_1_84;  // sfix14_En17
  input   signed [13:0] bhat_1_85;  // sfix14_En17
  input   signed [13:0] bhat_1_86;  // sfix14_En17
  input   signed [13:0] bhat_1_87;  // sfix14_En17
  input   signed [13:0] bhat_1_88;  // sfix14_En17
  input   signed [13:0] bhat_1_89;  // sfix14_En17
  output  signed [13:0] e_0;  // sfix14_En17
  output  signed [13:0] e_1;  // sfix14_En17
  output  signed [13:0] e_2;  // sfix14_En17
  output  signed [13:0] e_3;  // sfix14_En17
  output  signed [13:0] e_4;  // sfix14_En17
  output  signed [13:0] e_5;  // sfix14_En17
  output  signed [13:0] e_6;  // sfix14_En17
  output  signed [13:0] e_7;  // sfix14_En17
  output  signed [13:0] e_8;  // sfix14_En17
  output  signed [13:0] e_9;  // sfix14_En17
  output  signed [13:0] e_10;  // sfix14_En17
  output  signed [13:0] e_11;  // sfix14_En17
  output  signed [13:0] e_12;  // sfix14_En17
  output  signed [13:0] e_13;  // sfix14_En17
  output  signed [13:0] e_14;  // sfix14_En17
  output  signed [13:0] e_15;  // sfix14_En17
  output  signed [13:0] e_16;  // sfix14_En17
  output  signed [13:0] e_17;  // sfix14_En17
  output  signed [13:0] e_18;  // sfix14_En17
  output  signed [13:0] e_19;  // sfix14_En17
  output  signed [13:0] e_20;  // sfix14_En17
  output  signed [13:0] e_21;  // sfix14_En17
  output  signed [13:0] e_22;  // sfix14_En17
  output  signed [13:0] e_23;  // sfix14_En17
  output  signed [13:0] e_24;  // sfix14_En17
  output  signed [13:0] e_25;  // sfix14_En17
  output  signed [13:0] e_26;  // sfix14_En17
  output  signed [13:0] e_27;  // sfix14_En17
  output  signed [13:0] e_28;  // sfix14_En17
  output  signed [13:0] e_29;  // sfix14_En17
  output  signed [13:0] e_30;  // sfix14_En17
  output  signed [13:0] e_31;  // sfix14_En17
  output  signed [13:0] e_32;  // sfix14_En17
  output  signed [13:0] e_33;  // sfix14_En17
  output  signed [13:0] e_34;  // sfix14_En17
  output  signed [13:0] e_35;  // sfix14_En17
  output  signed [13:0] e_36;  // sfix14_En17
  output  signed [13:0] e_37;  // sfix14_En17
  output  signed [13:0] e_38;  // sfix14_En17
  output  signed [13:0] e_39;  // sfix14_En17
  output  signed [13:0] e_40;  // sfix14_En17
  output  signed [13:0] e_41;  // sfix14_En17
  output  signed [13:0] e_42;  // sfix14_En17
  output  signed [13:0] e_43;  // sfix14_En17
  output  signed [13:0] e_44;  // sfix14_En17
  output  signed [13:0] e_45;  // sfix14_En17
  output  signed [13:0] e_46;  // sfix14_En17
  output  signed [13:0] e_47;  // sfix14_En17
  output  signed [13:0] e_48;  // sfix14_En17
  output  signed [13:0] e_49;  // sfix14_En17
  output  signed [13:0] e_50;  // sfix14_En17
  output  signed [13:0] e_51;  // sfix14_En17
  output  signed [13:0] e_52;  // sfix14_En17
  output  signed [13:0] e_53;  // sfix14_En17
  output  signed [13:0] e_54;  // sfix14_En17
  output  signed [13:0] e_55;  // sfix14_En17
  output  signed [13:0] e_56;  // sfix14_En17
  output  signed [13:0] e_57;  // sfix14_En17
  output  signed [13:0] e_58;  // sfix14_En17
  output  signed [13:0] e_59;  // sfix14_En17
  output  signed [13:0] e_60;  // sfix14_En17
  output  signed [13:0] e_61;  // sfix14_En17
  output  signed [13:0] e_62;  // sfix14_En17
  output  signed [13:0] e_63;  // sfix14_En17
  output  signed [13:0] e_64;  // sfix14_En17
  output  signed [13:0] e_65;  // sfix14_En17
  output  signed [13:0] e_66;  // sfix14_En17
  output  signed [13:0] e_67;  // sfix14_En17
  output  signed [13:0] e_68;  // sfix14_En17
  output  signed [13:0] e_69;  // sfix14_En17
  output  signed [13:0] e_70;  // sfix14_En17
  output  signed [13:0] e_71;  // sfix14_En17
  output  signed [13:0] e_72;  // sfix14_En17
  output  signed [13:0] e_73;  // sfix14_En17
  output  signed [13:0] e_74;  // sfix14_En17
  output  signed [13:0] e_75;  // sfix14_En17
  output  signed [13:0] e_76;  // sfix14_En17
  output  signed [13:0] e_77;  // sfix14_En17
  output  signed [13:0] e_78;  // sfix14_En17
  output  signed [13:0] e_79;  // sfix14_En17
  output  signed [13:0] e_80;  // sfix14_En17
  output  signed [13:0] e_81;  // sfix14_En17
  output  signed [13:0] e_82;  // sfix14_En17
  output  signed [13:0] e_83;  // sfix14_En17
  output  signed [13:0] e_84;  // sfix14_En17
  output  signed [13:0] e_85;  // sfix14_En17
  output  signed [13:0] e_86;  // sfix14_En17
  output  signed [13:0] e_87;  // sfix14_En17
  output  signed [13:0] e_88;  // sfix14_En17
  output  signed [13:0] e_89;  // sfix14_En17
  output  signed [13:0] W;  // sfix14_En15
  output  signed [13:0] bhat_0;  // sfix14_En17
  output  signed [13:0] bhat_1;  // sfix14_En17
  output  signed [13:0] bhat_2;  // sfix14_En17
  output  signed [13:0] bhat_3;  // sfix14_En17
  output  signed [13:0] bhat_4;  // sfix14_En17
  output  signed [13:0] bhat_5;  // sfix14_En17
  output  signed [13:0] bhat_6;  // sfix14_En17
  output  signed [13:0] bhat_7;  // sfix14_En17
  output  signed [13:0] bhat_8;  // sfix14_En17
  output  signed [13:0] bhat_9;  // sfix14_En17
  output  signed [13:0] bhat_10;  // sfix14_En17
  output  signed [13:0] bhat_11;  // sfix14_En17
  output  signed [13:0] bhat_12;  // sfix14_En17
  output  signed [13:0] bhat_13;  // sfix14_En17
  output  signed [13:0] bhat_14;  // sfix14_En17
  output  signed [13:0] bhat_15;  // sfix14_En17
  output  signed [13:0] bhat_16;  // sfix14_En17
  output  signed [13:0] bhat_17;  // sfix14_En17
  output  signed [13:0] bhat_18;  // sfix14_En17
  output  signed [13:0] bhat_19;  // sfix14_En17
  output  signed [13:0] bhat_20;  // sfix14_En17
  output  signed [13:0] bhat_21;  // sfix14_En17
  output  signed [13:0] bhat_22;  // sfix14_En17
  output  signed [13:0] bhat_23;  // sfix14_En17
  output  signed [13:0] bhat_24;  // sfix14_En17
  output  signed [13:0] bhat_25;  // sfix14_En17
  output  signed [13:0] bhat_26;  // sfix14_En17
  output  signed [13:0] bhat_27;  // sfix14_En17
  output  signed [13:0] bhat_28;  // sfix14_En17
  output  signed [13:0] bhat_29;  // sfix14_En17
  output  signed [13:0] bhat_30;  // sfix14_En17
  output  signed [13:0] bhat_31;  // sfix14_En17
  output  signed [13:0] bhat_32;  // sfix14_En17
  output  signed [13:0] bhat_33;  // sfix14_En17
  output  signed [13:0] bhat_34;  // sfix14_En17
  output  signed [13:0] bhat_35;  // sfix14_En17
  output  signed [13:0] bhat_36;  // sfix14_En17
  output  signed [13:0] bhat_37;  // sfix14_En17
  output  signed [13:0] bhat_38;  // sfix14_En17
  output  signed [13:0] bhat_39;  // sfix14_En17
  output  signed [13:0] bhat_40;  // sfix14_En17
  output  signed [13:0] bhat_41;  // sfix14_En17
  output  signed [13:0] bhat_42;  // sfix14_En17
  output  signed [13:0] bhat_43;  // sfix14_En17
  output  signed [13:0] bhat_44;  // sfix14_En17
  output  signed [13:0] bhat_45;  // sfix14_En17
  output  signed [13:0] bhat_46;  // sfix14_En17
  output  signed [13:0] bhat_47;  // sfix14_En17
  output  signed [13:0] bhat_48;  // sfix14_En17
  output  signed [13:0] bhat_49;  // sfix14_En17
  output  signed [13:0] bhat_50;  // sfix14_En17
  output  signed [13:0] bhat_51;  // sfix14_En17
  output  signed [13:0] bhat_52;  // sfix14_En17
  output  signed [13:0] bhat_53;  // sfix14_En17
  output  signed [13:0] bhat_54;  // sfix14_En17
  output  signed [13:0] bhat_55;  // sfix14_En17
  output  signed [13:0] bhat_56;  // sfix14_En17
  output  signed [13:0] bhat_57;  // sfix14_En17
  output  signed [13:0] bhat_58;  // sfix14_En17
  output  signed [13:0] bhat_59;  // sfix14_En17
  output  signed [13:0] bhat_60;  // sfix14_En17
  output  signed [13:0] bhat_61;  // sfix14_En17
  output  signed [13:0] bhat_62;  // sfix14_En17
  output  signed [13:0] bhat_63;  // sfix14_En17
  output  signed [13:0] bhat_64;  // sfix14_En17
  output  signed [13:0] bhat_65;  // sfix14_En17
  output  signed [13:0] bhat_66;  // sfix14_En17
  output  signed [13:0] bhat_67;  // sfix14_En17
  output  signed [13:0] bhat_68;  // sfix14_En17
  output  signed [13:0] bhat_69;  // sfix14_En17
  output  signed [13:0] bhat_70;  // sfix14_En17
  output  signed [13:0] bhat_71;  // sfix14_En17
  output  signed [13:0] bhat_72;  // sfix14_En17
  output  signed [13:0] bhat_73;  // sfix14_En17
  output  signed [13:0] bhat_74;  // sfix14_En17
  output  signed [13:0] bhat_75;  // sfix14_En17
  output  signed [13:0] bhat_76;  // sfix14_En17
  output  signed [13:0] bhat_77;  // sfix14_En17
  output  signed [13:0] bhat_78;  // sfix14_En17
  output  signed [13:0] bhat_79;  // sfix14_En17
  output  signed [13:0] bhat_80;  // sfix14_En17
  output  signed [13:0] bhat_81;  // sfix14_En17
  output  signed [13:0] bhat_82;  // sfix14_En17
  output  signed [13:0] bhat_83;  // sfix14_En17
  output  signed [13:0] bhat_84;  // sfix14_En17
  output  signed [13:0] bhat_85;  // sfix14_En17
  output  signed [13:0] bhat_86;  // sfix14_En17
  output  signed [13:0] bhat_87;  // sfix14_En17
  output  signed [13:0] bhat_88;  // sfix14_En17
  output  signed [13:0] bhat_89;  // sfix14_En17

  wire signed [13:0] s [0:99];  // sfix14_En17 [100]
  wire signed [13:0] n [0:99];  // sfix14_En15 [100]
  wire signed [13:0] e_1_90 [0:89];  // sfix14_En17 [90]
  wire signed [13:0] bhat_1_90 [0:89];  // sfix14_En17 [90]
  reg signed [13:0] e [0:89];  // sfix14_En17 [90]
  reg signed [13:0] W_2;  // sfix14_En15
  reg signed [13:0] bhat [0:89];  // sfix14_En17 [90]
  reg signed [13:0] noise_cancel_fixpt_bhat [0:89];  // sfix14_En17 [90]
  reg signed [13:0] noise_cancel_fixpt_e [0:89];  // sfix14_En17 [90]
  reg signed [13:0] noise_cancel_fixpt_e_0 [0:89];  // sfix14_En17 [90]
  reg signed [31:0] noise_cancel_fixpt_i;  // int32
  reg signed [9:0] noise_cancel_fixpt_i_0;  // sfix10
  reg signed [13:0] noise_cancel_fixpt_bhat_0 [0:89];  // sfix14_En17 [90]
  reg signed [31:0] noise_cancel_fixpt_i_1;  // int32
  reg signed [9:0] noise_cancel_fixpt_i_2;  // sfix10
  reg signed [31:0] noise_cancel_fixpt_t_0;  // int32
  reg signed [31:0] noise_cancel_fixpt_t_1;  // int32
  reg signed [31:0] noise_cancel_fixpt_t_2;  // int32
  reg signed [10:0] noise_cancel_fixpt_add_temp [0:88];  // sfix11 [89]
  reg signed [12:0] noise_cancel_fixpt_sub_temp [0:88];  // sfix13 [89]
  reg signed [31:0] noise_cancel_fixpt_add_temp_0 [0:88];  // int32 [89]
  reg signed [18:0] noise_cancel_fixpt_sub_cast [0:88];  // sfix19_En21 [89]
  reg signed [10:0] noise_cancel_fixpt_add_temp_1 [0:88];  // sfix11 [89]
  reg signed [12:0] noise_cancel_fixpt_sub_temp_0 [0:88];  // sfix13 [89]
  reg signed [27:0] noise_cancel_fixpt_mul_temp [0:88];  // sfix28_En32 [89]
  reg signed [13:0] noise_cancel_fixpt_sub_cast_0 [0:88];  // sfix14_En21 [89]
  reg signed [18:0] noise_cancel_fixpt_sub_cast_1 [0:88];  // sfix19_En21 [89]
  reg signed [18:0] noise_cancel_fixpt_sub_temp_1 [0:88];  // sfix19_En21 [89]
  reg signed [11:0] noise_cancel_fixpt_add_temp_2 [0:88];  // sfix12 [89]
  reg signed [29:0] noise_cancel_fixpt_add_cast [0:88];  // sfix30_En32 [89]
  reg signed [10:0] noise_cancel_fixpt_add_temp_3 [0:88];  // sfix11 [89]
  reg signed [12:0] noise_cancel_fixpt_sub_temp_2 [0:88];  // sfix13 [89]
  reg signed [27:0] noise_cancel_fixpt_mul_temp_0 [0:88];  // sfix28_En32 [89]
  reg signed [28:0] noise_cancel_fixpt_add_cast_0 [0:88];  // sfix29_En32 [89]
  reg signed [29:0] noise_cancel_fixpt_add_cast_1 [0:88];  // sfix30_En32 [89]
  reg signed [29:0] noise_cancel_fixpt_add_temp_4 [0:88];  // sfix30_En32 [89]
  reg signed [31:0] noise_cancel_fixpt_add_temp_5 [0:88];  // int32 [89]
  reg signed [18:0] noise_cancel_fixpt_sub_cast_2 [0:88];  // sfix19_En21 [89]
  reg signed [10:0] noise_cancel_fixpt_add_temp_6 [0:88];  // sfix11 [89]
  reg signed [12:0] noise_cancel_fixpt_sub_temp_3 [0:88];  // sfix13 [89]
  reg signed [27:0] noise_cancel_fixpt_mul_temp_1 [0:88];  // sfix28_En32 [89]
  reg signed [13:0] noise_cancel_fixpt_sub_cast_3 [0:88];  // sfix14_En21 [89]
  reg signed [18:0] noise_cancel_fixpt_sub_cast_4 [0:88];  // sfix19_En21 [89]
  reg signed [18:0] noise_cancel_fixpt_sub_temp_4 [0:88];  // sfix19_En21 [89]
  reg signed [11:0] noise_cancel_fixpt_add_temp_7 [0:88];  // sfix12 [89]
  reg signed [29:0] noise_cancel_fixpt_add_cast_2 [0:88];  // sfix30_En32 [89]
  reg signed [10:0] noise_cancel_fixpt_add_temp_8 [0:88];  // sfix11 [89]
  reg signed [12:0] noise_cancel_fixpt_sub_temp_5 [0:88];  // sfix13 [89]
  reg signed [27:0] noise_cancel_fixpt_mul_temp_2 [0:88];  // sfix28_En32 [89]
  reg signed [28:0] noise_cancel_fixpt_add_cast_3 [0:88];  // sfix29_En32 [89]
  reg signed [29:0] noise_cancel_fixpt_add_cast_4 [0:88];  // sfix30_En32 [89]
  reg signed [29:0] noise_cancel_fixpt_add_temp_9 [0:88];  // sfix30_En32 [89]
  reg signed [31:0] noise_cancel_fixpt_add_temp_10 [0:88];  // int32 [89]
  reg signed [9:0] noise_cancel_fixpt_t_3 [0:88];  // sfix10 [89]
  reg signed [10:0] noise_cancel_fixpt_t_4 [0:88];  // sfix11 [89]
  reg signed [12:0] noise_cancel_fixpt_t_5 [0:88];  // sfix13 [89]
  reg signed [10:0] noise_cancel_fixpt_t_6 [0:88];  // sfix11 [89]
  reg signed [12:0] noise_cancel_fixpt_t_7 [0:88];  // sfix13 [89]
  reg signed [11:0] noise_cancel_fixpt_t_8 [0:88];  // sfix12 [89]
  reg signed [10:0] noise_cancel_fixpt_t_9 [0:88];  // sfix11 [89]
  reg signed [12:0] noise_cancel_fixpt_t_10 [0:88];  // sfix13 [89]
  reg signed [10:0] noise_cancel_fixpt_t_11 [0:88];  // sfix11 [89]
  reg signed [12:0] noise_cancel_fixpt_t_12 [0:88];  // sfix13 [89]
  reg signed [11:0] noise_cancel_fixpt_t_13 [0:88];  // sfix12 [89]
  reg signed [10:0] noise_cancel_fixpt_t_14 [0:88];  // sfix11 [89]
  reg signed [12:0] noise_cancel_fixpt_t_15 [0:88];  // sfix13 [89]


  assign s[0] = s_0;
  assign s[1] = s_1;
  assign s[2] = s_2;
  assign s[3] = s_3;
  assign s[4] = s_4;
  assign s[5] = s_5;
  assign s[6] = s_6;
  assign s[7] = s_7;
  assign s[8] = s_8;
  assign s[9] = s_9;
  assign s[10] = s_10;
  assign s[11] = s_11;
  assign s[12] = s_12;
  assign s[13] = s_13;
  assign s[14] = s_14;
  assign s[15] = s_15;
  assign s[16] = s_16;
  assign s[17] = s_17;
  assign s[18] = s_18;
  assign s[19] = s_19;
  assign s[20] = s_20;
  assign s[21] = s_21;
  assign s[22] = s_22;
  assign s[23] = s_23;
  assign s[24] = s_24;
  assign s[25] = s_25;
  assign s[26] = s_26;
  assign s[27] = s_27;
  assign s[28] = s_28;
  assign s[29] = s_29;
  assign s[30] = s_30;
  assign s[31] = s_31;
  assign s[32] = s_32;
  assign s[33] = s_33;
  assign s[34] = s_34;
  assign s[35] = s_35;
  assign s[36] = s_36;
  assign s[37] = s_37;
  assign s[38] = s_38;
  assign s[39] = s_39;
  assign s[40] = s_40;
  assign s[41] = s_41;
  assign s[42] = s_42;
  assign s[43] = s_43;
  assign s[44] = s_44;
  assign s[45] = s_45;
  assign s[46] = s_46;
  assign s[47] = s_47;
  assign s[48] = s_48;
  assign s[49] = s_49;
  assign s[50] = s_50;
  assign s[51] = s_51;
  assign s[52] = s_52;
  assign s[53] = s_53;
  assign s[54] = s_54;
  assign s[55] = s_55;
  assign s[56] = s_56;
  assign s[57] = s_57;
  assign s[58] = s_58;
  assign s[59] = s_59;
  assign s[60] = s_60;
  assign s[61] = s_61;
  assign s[62] = s_62;
  assign s[63] = s_63;
  assign s[64] = s_64;
  assign s[65] = s_65;
  assign s[66] = s_66;
  assign s[67] = s_67;
  assign s[68] = s_68;
  assign s[69] = s_69;
  assign s[70] = s_70;
  assign s[71] = s_71;
  assign s[72] = s_72;
  assign s[73] = s_73;
  assign s[74] = s_74;
  assign s[75] = s_75;
  assign s[76] = s_76;
  assign s[77] = s_77;
  assign s[78] = s_78;
  assign s[79] = s_79;
  assign s[80] = s_80;
  assign s[81] = s_81;
  assign s[82] = s_82;
  assign s[83] = s_83;
  assign s[84] = s_84;
  assign s[85] = s_85;
  assign s[86] = s_86;
  assign s[87] = s_87;
  assign s[88] = s_88;
  assign s[89] = s_89;
  assign s[90] = s_90;
  assign s[91] = s_91;
  assign s[92] = s_92;
  assign s[93] = s_93;
  assign s[94] = s_94;
  assign s[95] = s_95;
  assign s[96] = s_96;
  assign s[97] = s_97;
  assign s[98] = s_98;
  assign s[99] = s_99;

  assign n[0] = n_0;
  assign n[1] = n_1;
  assign n[2] = n_2;
  assign n[3] = n_3;
  assign n[4] = n_4;
  assign n[5] = n_5;
  assign n[6] = n_6;
  assign n[7] = n_7;
  assign n[8] = n_8;
  assign n[9] = n_9;
  assign n[10] = n_10;
  assign n[11] = n_11;
  assign n[12] = n_12;
  assign n[13] = n_13;
  assign n[14] = n_14;
  assign n[15] = n_15;
  assign n[16] = n_16;
  assign n[17] = n_17;
  assign n[18] = n_18;
  assign n[19] = n_19;
  assign n[20] = n_20;
  assign n[21] = n_21;
  assign n[22] = n_22;
  assign n[23] = n_23;
  assign n[24] = n_24;
  assign n[25] = n_25;
  assign n[26] = n_26;
  assign n[27] = n_27;
  assign n[28] = n_28;
  assign n[29] = n_29;
  assign n[30] = n_30;
  assign n[31] = n_31;
  assign n[32] = n_32;
  assign n[33] = n_33;
  assign n[34] = n_34;
  assign n[35] = n_35;
  assign n[36] = n_36;
  assign n[37] = n_37;
  assign n[38] = n_38;
  assign n[39] = n_39;
  assign n[40] = n_40;
  assign n[41] = n_41;
  assign n[42] = n_42;
  assign n[43] = n_43;
  assign n[44] = n_44;
  assign n[45] = n_45;
  assign n[46] = n_46;
  assign n[47] = n_47;
  assign n[48] = n_48;
  assign n[49] = n_49;
  assign n[50] = n_50;
  assign n[51] = n_51;
  assign n[52] = n_52;
  assign n[53] = n_53;
  assign n[54] = n_54;
  assign n[55] = n_55;
  assign n[56] = n_56;
  assign n[57] = n_57;
  assign n[58] = n_58;
  assign n[59] = n_59;
  assign n[60] = n_60;
  assign n[61] = n_61;
  assign n[62] = n_62;
  assign n[63] = n_63;
  assign n[64] = n_64;
  assign n[65] = n_65;
  assign n[66] = n_66;
  assign n[67] = n_67;
  assign n[68] = n_68;
  assign n[69] = n_69;
  assign n[70] = n_70;
  assign n[71] = n_71;
  assign n[72] = n_72;
  assign n[73] = n_73;
  assign n[74] = n_74;
  assign n[75] = n_75;
  assign n[76] = n_76;
  assign n[77] = n_77;
  assign n[78] = n_78;
  assign n[79] = n_79;
  assign n[80] = n_80;
  assign n[81] = n_81;
  assign n[82] = n_82;
  assign n[83] = n_83;
  assign n[84] = n_84;
  assign n[85] = n_85;
  assign n[86] = n_86;
  assign n[87] = n_87;
  assign n[88] = n_88;
  assign n[89] = n_89;
  assign n[90] = n_90;
  assign n[91] = n_91;
  assign n[92] = n_92;
  assign n[93] = n_93;
  assign n[94] = n_94;
  assign n[95] = n_95;
  assign n[96] = n_96;
  assign n[97] = n_97;
  assign n[98] = n_98;
  assign n[99] = n_99;

  assign e_1_90[0] = e_1_0;
  assign e_1_90[1] = e_1_1;
  assign e_1_90[2] = e_1_2;
  assign e_1_90[3] = e_1_3;
  assign e_1_90[4] = e_1_4;
  assign e_1_90[5] = e_1_5;
  assign e_1_90[6] = e_1_6;
  assign e_1_90[7] = e_1_7;
  assign e_1_90[8] = e_1_8;
  assign e_1_90[9] = e_1_9;
  assign e_1_90[10] = e_1_10;
  assign e_1_90[11] = e_1_11;
  assign e_1_90[12] = e_1_12;
  assign e_1_90[13] = e_1_13;
  assign e_1_90[14] = e_1_14;
  assign e_1_90[15] = e_1_15;
  assign e_1_90[16] = e_1_16;
  assign e_1_90[17] = e_1_17;
  assign e_1_90[18] = e_1_18;
  assign e_1_90[19] = e_1_19;
  assign e_1_90[20] = e_1_20;
  assign e_1_90[21] = e_1_21;
  assign e_1_90[22] = e_1_22;
  assign e_1_90[23] = e_1_23;
  assign e_1_90[24] = e_1_24;
  assign e_1_90[25] = e_1_25;
  assign e_1_90[26] = e_1_26;
  assign e_1_90[27] = e_1_27;
  assign e_1_90[28] = e_1_28;
  assign e_1_90[29] = e_1_29;
  assign e_1_90[30] = e_1_30;
  assign e_1_90[31] = e_1_31;
  assign e_1_90[32] = e_1_32;
  assign e_1_90[33] = e_1_33;
  assign e_1_90[34] = e_1_34;
  assign e_1_90[35] = e_1_35;
  assign e_1_90[36] = e_1_36;
  assign e_1_90[37] = e_1_37;
  assign e_1_90[38] = e_1_38;
  assign e_1_90[39] = e_1_39;
  assign e_1_90[40] = e_1_40;
  assign e_1_90[41] = e_1_41;
  assign e_1_90[42] = e_1_42;
  assign e_1_90[43] = e_1_43;
  assign e_1_90[44] = e_1_44;
  assign e_1_90[45] = e_1_45;
  assign e_1_90[46] = e_1_46;
  assign e_1_90[47] = e_1_47;
  assign e_1_90[48] = e_1_48;
  assign e_1_90[49] = e_1_49;
  assign e_1_90[50] = e_1_50;
  assign e_1_90[51] = e_1_51;
  assign e_1_90[52] = e_1_52;
  assign e_1_90[53] = e_1_53;
  assign e_1_90[54] = e_1_54;
  assign e_1_90[55] = e_1_55;
  assign e_1_90[56] = e_1_56;
  assign e_1_90[57] = e_1_57;
  assign e_1_90[58] = e_1_58;
  assign e_1_90[59] = e_1_59;
  assign e_1_90[60] = e_1_60;
  assign e_1_90[61] = e_1_61;
  assign e_1_90[62] = e_1_62;
  assign e_1_90[63] = e_1_63;
  assign e_1_90[64] = e_1_64;
  assign e_1_90[65] = e_1_65;
  assign e_1_90[66] = e_1_66;
  assign e_1_90[67] = e_1_67;
  assign e_1_90[68] = e_1_68;
  assign e_1_90[69] = e_1_69;
  assign e_1_90[70] = e_1_70;
  assign e_1_90[71] = e_1_71;
  assign e_1_90[72] = e_1_72;
  assign e_1_90[73] = e_1_73;
  assign e_1_90[74] = e_1_74;
  assign e_1_90[75] = e_1_75;
  assign e_1_90[76] = e_1_76;
  assign e_1_90[77] = e_1_77;
  assign e_1_90[78] = e_1_78;
  assign e_1_90[79] = e_1_79;
  assign e_1_90[80] = e_1_80;
  assign e_1_90[81] = e_1_81;
  assign e_1_90[82] = e_1_82;
  assign e_1_90[83] = e_1_83;
  assign e_1_90[84] = e_1_84;
  assign e_1_90[85] = e_1_85;
  assign e_1_90[86] = e_1_86;
  assign e_1_90[87] = e_1_87;
  assign e_1_90[88] = e_1_88;
  assign e_1_90[89] = e_1_89;

  assign bhat_1_90[0] = bhat_1_0;
  assign bhat_1_90[1] = bhat_1_1;
  assign bhat_1_90[2] = bhat_1_2;
  assign bhat_1_90[3] = bhat_1_3;
  assign bhat_1_90[4] = bhat_1_4;
  assign bhat_1_90[5] = bhat_1_5;
  assign bhat_1_90[6] = bhat_1_6;
  assign bhat_1_90[7] = bhat_1_7;
  assign bhat_1_90[8] = bhat_1_8;
  assign bhat_1_90[9] = bhat_1_9;
  assign bhat_1_90[10] = bhat_1_10;
  assign bhat_1_90[11] = bhat_1_11;
  assign bhat_1_90[12] = bhat_1_12;
  assign bhat_1_90[13] = bhat_1_13;
  assign bhat_1_90[14] = bhat_1_14;
  assign bhat_1_90[15] = bhat_1_15;
  assign bhat_1_90[16] = bhat_1_16;
  assign bhat_1_90[17] = bhat_1_17;
  assign bhat_1_90[18] = bhat_1_18;
  assign bhat_1_90[19] = bhat_1_19;
  assign bhat_1_90[20] = bhat_1_20;
  assign bhat_1_90[21] = bhat_1_21;
  assign bhat_1_90[22] = bhat_1_22;
  assign bhat_1_90[23] = bhat_1_23;
  assign bhat_1_90[24] = bhat_1_24;
  assign bhat_1_90[25] = bhat_1_25;
  assign bhat_1_90[26] = bhat_1_26;
  assign bhat_1_90[27] = bhat_1_27;
  assign bhat_1_90[28] = bhat_1_28;
  assign bhat_1_90[29] = bhat_1_29;
  assign bhat_1_90[30] = bhat_1_30;
  assign bhat_1_90[31] = bhat_1_31;
  assign bhat_1_90[32] = bhat_1_32;
  assign bhat_1_90[33] = bhat_1_33;
  assign bhat_1_90[34] = bhat_1_34;
  assign bhat_1_90[35] = bhat_1_35;
  assign bhat_1_90[36] = bhat_1_36;
  assign bhat_1_90[37] = bhat_1_37;
  assign bhat_1_90[38] = bhat_1_38;
  assign bhat_1_90[39] = bhat_1_39;
  assign bhat_1_90[40] = bhat_1_40;
  assign bhat_1_90[41] = bhat_1_41;
  assign bhat_1_90[42] = bhat_1_42;
  assign bhat_1_90[43] = bhat_1_43;
  assign bhat_1_90[44] = bhat_1_44;
  assign bhat_1_90[45] = bhat_1_45;
  assign bhat_1_90[46] = bhat_1_46;
  assign bhat_1_90[47] = bhat_1_47;
  assign bhat_1_90[48] = bhat_1_48;
  assign bhat_1_90[49] = bhat_1_49;
  assign bhat_1_90[50] = bhat_1_50;
  assign bhat_1_90[51] = bhat_1_51;
  assign bhat_1_90[52] = bhat_1_52;
  assign bhat_1_90[53] = bhat_1_53;
  assign bhat_1_90[54] = bhat_1_54;
  assign bhat_1_90[55] = bhat_1_55;
  assign bhat_1_90[56] = bhat_1_56;
  assign bhat_1_90[57] = bhat_1_57;
  assign bhat_1_90[58] = bhat_1_58;
  assign bhat_1_90[59] = bhat_1_59;
  assign bhat_1_90[60] = bhat_1_60;
  assign bhat_1_90[61] = bhat_1_61;
  assign bhat_1_90[62] = bhat_1_62;
  assign bhat_1_90[63] = bhat_1_63;
  assign bhat_1_90[64] = bhat_1_64;
  assign bhat_1_90[65] = bhat_1_65;
  assign bhat_1_90[66] = bhat_1_66;
  assign bhat_1_90[67] = bhat_1_67;
  assign bhat_1_90[68] = bhat_1_68;
  assign bhat_1_90[69] = bhat_1_69;
  assign bhat_1_90[70] = bhat_1_70;
  assign bhat_1_90[71] = bhat_1_71;
  assign bhat_1_90[72] = bhat_1_72;
  assign bhat_1_90[73] = bhat_1_73;
  assign bhat_1_90[74] = bhat_1_74;
  assign bhat_1_90[75] = bhat_1_75;
  assign bhat_1_90[76] = bhat_1_76;
  assign bhat_1_90[77] = bhat_1_77;
  assign bhat_1_90[78] = bhat_1_78;
  assign bhat_1_90[79] = bhat_1_79;
  assign bhat_1_90[80] = bhat_1_80;
  assign bhat_1_90[81] = bhat_1_81;
  assign bhat_1_90[82] = bhat_1_82;
  assign bhat_1_90[83] = bhat_1_83;
  assign bhat_1_90[84] = bhat_1_84;
  assign bhat_1_90[85] = bhat_1_85;
  assign bhat_1_90[86] = bhat_1_86;
  assign bhat_1_90[87] = bhat_1_87;
  assign bhat_1_90[88] = bhat_1_88;
  assign bhat_1_90[89] = bhat_1_89;

  always @* begin
    //HDL code generation from MATLAB function: noise_cancel_fixpt
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    //                                                                          %
    //           Generated by MATLAB 9.2 and Fixed-Point Designer 5.4           %
    //                                                                          %
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    //UNTITLED Summary of this function goes here
    //   Detailed explanation goes here
    // p=inputParser;
    // argName='bhat W e';
    // default=[zeros(1,itno) zeros(1,size(bhat,1)) zeros(1,itno)] ;
    // % argName1='W';
    // % default=zeros(1,size(bhat,1));
    // % argName2='e';
    // % default=zeros(1,itno);
    // addOptional(p,argName,default);

    for(noise_cancel_fixpt_t_0 = 32'sd0; noise_cancel_fixpt_t_0 <= 32'sd89; noise_cancel_fixpt_t_0 = noise_cancel_fixpt_t_0 + 32'sd1) begin
      noise_cancel_fixpt_bhat[noise_cancel_fixpt_t_0] = 14'sb00000000000000;
      noise_cancel_fixpt_e[noise_cancel_fixpt_t_0] = 14'sb00000000000000;
    end

    // if nargin < 2
    //   error('signal and noise are required inputs')
    // end
    // 
    // if nargin < 3
    //   e = zeros(1,itno);
    //   W=zeros(1,size(bhat,1));
    //   bhat=zeros(1,itno);
    // end
    // 
    // if nargin < 4
    //   W=zeros(1,size(bhat,1));
    //   bhat=zeros(1,itno);
    // end
    // if nargin < 5
    //     bhat=zeros(1,itno);
    // end
    // 
    W_2 = 14'sb00000000000000;

    for(noise_cancel_fixpt_i = 32'sd0; noise_cancel_fixpt_i <= 32'sd88; noise_cancel_fixpt_i = noise_cancel_fixpt_i + 32'sd1) begin
      noise_cancel_fixpt_add_temp_10[noise_cancel_fixpt_i] = noise_cancel_fixpt_i + 32'sd1;
      noise_cancel_fixpt_t_3[noise_cancel_fixpt_i] = noise_cancel_fixpt_add_temp_10[noise_cancel_fixpt_i][9:0];
      noise_cancel_fixpt_t_4[noise_cancel_fixpt_i] = {noise_cancel_fixpt_t_3[noise_cancel_fixpt_i][9], noise_cancel_fixpt_t_3[noise_cancel_fixpt_i]};
      noise_cancel_fixpt_add_temp[noise_cancel_fixpt_i] = noise_cancel_fixpt_t_4[noise_cancel_fixpt_i] + 11'sb00000000001;
      noise_cancel_fixpt_t_5[noise_cancel_fixpt_i] = {{2{noise_cancel_fixpt_add_temp[noise_cancel_fixpt_i][10]}}, noise_cancel_fixpt_add_temp[noise_cancel_fixpt_i]};
      noise_cancel_fixpt_sub_temp[noise_cancel_fixpt_i] = noise_cancel_fixpt_t_5[noise_cancel_fixpt_i] - 13'sb0000000000001;
      W_2 = n[noise_cancel_fixpt_sub_temp[noise_cancel_fixpt_i] - 32'sd1];
    end


    for(noise_cancel_fixpt_t_1 = 32'sd0; noise_cancel_fixpt_t_1 <= 32'sd89; noise_cancel_fixpt_t_1 = noise_cancel_fixpt_t_1 + 32'sd1) begin
      noise_cancel_fixpt_bhat_0[noise_cancel_fixpt_t_1] = noise_cancel_fixpt_bhat[noise_cancel_fixpt_t_1];
      noise_cancel_fixpt_e_0[noise_cancel_fixpt_t_1] = noise_cancel_fixpt_e[noise_cancel_fixpt_t_1];
    end


    for(noise_cancel_fixpt_i_1 = 32'sd0; noise_cancel_fixpt_i_1 <= 32'sd88; noise_cancel_fixpt_i_1 = noise_cancel_fixpt_i_1 + 32'sd1) begin
      noise_cancel_fixpt_add_temp_0[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_i_1 + 32'sd1;
      noise_cancel_fixpt_i_0 = noise_cancel_fixpt_add_temp_0[noise_cancel_fixpt_i_1][9:0];
      noise_cancel_fixpt_sub_cast[noise_cancel_fixpt_i_1] = {s[noise_cancel_fixpt_i_0 - 32'sd1][13], {s[noise_cancel_fixpt_i_0 - 32'sd1], 4'b0000}};
      noise_cancel_fixpt_t_6[noise_cancel_fixpt_i_1] = {noise_cancel_fixpt_i_0[9], noise_cancel_fixpt_i_0};
      noise_cancel_fixpt_add_temp_1[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_t_6[noise_cancel_fixpt_i_1] + 11'sb00000000001;
      noise_cancel_fixpt_t_7[noise_cancel_fixpt_i_1] = {{2{noise_cancel_fixpt_add_temp_1[noise_cancel_fixpt_i_1][10]}}, noise_cancel_fixpt_add_temp_1[noise_cancel_fixpt_i_1]};
      noise_cancel_fixpt_sub_temp_0[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_t_7[noise_cancel_fixpt_i_1] - 13'sb0000000000001;
      noise_cancel_fixpt_mul_temp[noise_cancel_fixpt_i_1] = n[noise_cancel_fixpt_sub_temp_0[noise_cancel_fixpt_i_1] - 32'sd1] * noise_cancel_fixpt_bhat_0[noise_cancel_fixpt_i_0 - 32'sd1];
      noise_cancel_fixpt_sub_cast_0[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_mul_temp[noise_cancel_fixpt_i_1][24:11];
      noise_cancel_fixpt_sub_cast_1[noise_cancel_fixpt_i_1] = {{5{noise_cancel_fixpt_sub_cast_0[noise_cancel_fixpt_i_1][13]}}, noise_cancel_fixpt_sub_cast_0[noise_cancel_fixpt_i_1]};
      noise_cancel_fixpt_sub_temp_1[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_sub_cast[noise_cancel_fixpt_i_1] - noise_cancel_fixpt_sub_cast_1[noise_cancel_fixpt_i_1];
      noise_cancel_fixpt_e_0[noise_cancel_fixpt_i_0 - 32'sd1] = noise_cancel_fixpt_sub_temp_1[noise_cancel_fixpt_i_1][17:4];
      noise_cancel_fixpt_t_8[noise_cancel_fixpt_i_1] = {{2{noise_cancel_fixpt_i_0[9]}}, noise_cancel_fixpt_i_0};
      noise_cancel_fixpt_add_temp_2[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_t_8[noise_cancel_fixpt_i_1] + 12'sb000000000001;
      noise_cancel_fixpt_add_cast[noise_cancel_fixpt_i_1] = {noise_cancel_fixpt_bhat_0[noise_cancel_fixpt_i_0 - 32'sd1][13], {noise_cancel_fixpt_bhat_0[noise_cancel_fixpt_i_0 - 32'sd1], 15'b000000000000000}};
      noise_cancel_fixpt_t_9[noise_cancel_fixpt_i_1] = {noise_cancel_fixpt_i_0[9], noise_cancel_fixpt_i_0};
      noise_cancel_fixpt_add_temp_3[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_t_9[noise_cancel_fixpt_i_1] + 11'sb00000000001;
      noise_cancel_fixpt_t_10[noise_cancel_fixpt_i_1] = {{2{noise_cancel_fixpt_add_temp_3[noise_cancel_fixpt_i_1][10]}}, noise_cancel_fixpt_add_temp_3[noise_cancel_fixpt_i_1]};
      noise_cancel_fixpt_sub_temp_2[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_t_10[noise_cancel_fixpt_i_1] - 13'sb0000000000001;
      noise_cancel_fixpt_mul_temp_0[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_e_0[noise_cancel_fixpt_i_0 - 32'sd1] * n[noise_cancel_fixpt_sub_temp_2[noise_cancel_fixpt_i_1] - 32'sd1];
      noise_cancel_fixpt_add_cast_0[noise_cancel_fixpt_i_1] = {noise_cancel_fixpt_mul_temp_0[noise_cancel_fixpt_i_1][27], noise_cancel_fixpt_mul_temp_0[noise_cancel_fixpt_i_1]};
      noise_cancel_fixpt_add_cast_1[noise_cancel_fixpt_i_1] = {noise_cancel_fixpt_add_cast_0[noise_cancel_fixpt_i_1][28], noise_cancel_fixpt_add_cast_0[noise_cancel_fixpt_i_1]};
      noise_cancel_fixpt_add_temp_4[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_add_cast[noise_cancel_fixpt_i_1] + noise_cancel_fixpt_add_cast_1[noise_cancel_fixpt_i_1];
      noise_cancel_fixpt_bhat_0[noise_cancel_fixpt_add_temp_2[noise_cancel_fixpt_i_1] - 32'sd1] = noise_cancel_fixpt_add_temp_4[noise_cancel_fixpt_i_1][28:15];
      noise_cancel_fixpt_add_temp_5[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_i_1 + 32'sd1;
      noise_cancel_fixpt_i_2 = noise_cancel_fixpt_add_temp_5[noise_cancel_fixpt_i_1][9:0];
      noise_cancel_fixpt_sub_cast_2[noise_cancel_fixpt_i_1] = {s[noise_cancel_fixpt_i_2 - 32'sd1][13], {s[noise_cancel_fixpt_i_2 - 32'sd1], 4'b0000}};
      noise_cancel_fixpt_t_11[noise_cancel_fixpt_i_1] = {noise_cancel_fixpt_i_2[9], noise_cancel_fixpt_i_2};
      noise_cancel_fixpt_add_temp_6[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_t_11[noise_cancel_fixpt_i_1] + 11'sb00000000001;
      noise_cancel_fixpt_t_12[noise_cancel_fixpt_i_1] = {{2{noise_cancel_fixpt_add_temp_6[noise_cancel_fixpt_i_1][10]}}, noise_cancel_fixpt_add_temp_6[noise_cancel_fixpt_i_1]};
      noise_cancel_fixpt_sub_temp_3[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_t_12[noise_cancel_fixpt_i_1] - 13'sb0000000000001;
      noise_cancel_fixpt_mul_temp_1[noise_cancel_fixpt_i_1] = n[noise_cancel_fixpt_sub_temp_3[noise_cancel_fixpt_i_1] - 32'sd1] * noise_cancel_fixpt_bhat[noise_cancel_fixpt_i_2 - 32'sd1];
      noise_cancel_fixpt_sub_cast_3[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_mul_temp_1[noise_cancel_fixpt_i_1][24:11];
      noise_cancel_fixpt_sub_cast_4[noise_cancel_fixpt_i_1] = {{5{noise_cancel_fixpt_sub_cast_3[noise_cancel_fixpt_i_1][13]}}, noise_cancel_fixpt_sub_cast_3[noise_cancel_fixpt_i_1]};
      noise_cancel_fixpt_sub_temp_4[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_sub_cast_2[noise_cancel_fixpt_i_1] - noise_cancel_fixpt_sub_cast_4[noise_cancel_fixpt_i_1];
      noise_cancel_fixpt_e[noise_cancel_fixpt_i_2 - 32'sd1] = noise_cancel_fixpt_sub_temp_4[noise_cancel_fixpt_i_1][17:4];
      noise_cancel_fixpt_t_13[noise_cancel_fixpt_i_1] = {{2{noise_cancel_fixpt_i_2[9]}}, noise_cancel_fixpt_i_2};
      noise_cancel_fixpt_add_temp_7[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_t_13[noise_cancel_fixpt_i_1] + 12'sb000000000001;
      noise_cancel_fixpt_add_cast_2[noise_cancel_fixpt_i_1] = {noise_cancel_fixpt_bhat[noise_cancel_fixpt_i_2 - 32'sd1][13], {noise_cancel_fixpt_bhat[noise_cancel_fixpt_i_2 - 32'sd1], 15'b000000000000000}};
      noise_cancel_fixpt_t_14[noise_cancel_fixpt_i_1] = {noise_cancel_fixpt_i_2[9], noise_cancel_fixpt_i_2};
      noise_cancel_fixpt_add_temp_8[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_t_14[noise_cancel_fixpt_i_1] + 11'sb00000000001;
      noise_cancel_fixpt_t_15[noise_cancel_fixpt_i_1] = {{2{noise_cancel_fixpt_add_temp_8[noise_cancel_fixpt_i_1][10]}}, noise_cancel_fixpt_add_temp_8[noise_cancel_fixpt_i_1]};
      noise_cancel_fixpt_sub_temp_5[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_t_15[noise_cancel_fixpt_i_1] - 13'sb0000000000001;
      noise_cancel_fixpt_mul_temp_2[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_e[noise_cancel_fixpt_i_2 - 32'sd1] * n[noise_cancel_fixpt_sub_temp_5[noise_cancel_fixpt_i_1] - 32'sd1];
      noise_cancel_fixpt_add_cast_3[noise_cancel_fixpt_i_1] = {noise_cancel_fixpt_mul_temp_2[noise_cancel_fixpt_i_1][27], noise_cancel_fixpt_mul_temp_2[noise_cancel_fixpt_i_1]};
      noise_cancel_fixpt_add_cast_4[noise_cancel_fixpt_i_1] = {noise_cancel_fixpt_add_cast_3[noise_cancel_fixpt_i_1][28], noise_cancel_fixpt_add_cast_3[noise_cancel_fixpt_i_1]};
      noise_cancel_fixpt_add_temp_9[noise_cancel_fixpt_i_1] = noise_cancel_fixpt_add_cast_2[noise_cancel_fixpt_i_1] + noise_cancel_fixpt_add_cast_4[noise_cancel_fixpt_i_1];
      noise_cancel_fixpt_bhat[noise_cancel_fixpt_add_temp_7[noise_cancel_fixpt_i_1] - 32'sd1] = noise_cancel_fixpt_add_temp_9[noise_cancel_fixpt_i_1][28:15];
    end


    for(noise_cancel_fixpt_t_2 = 32'sd0; noise_cancel_fixpt_t_2 <= 32'sd89; noise_cancel_fixpt_t_2 = noise_cancel_fixpt_t_2 + 32'sd1) begin
      bhat[noise_cancel_fixpt_t_2] = noise_cancel_fixpt_bhat[noise_cancel_fixpt_t_2];
      e[noise_cancel_fixpt_t_2] = noise_cancel_fixpt_e_0[noise_cancel_fixpt_t_2];
    end

  end



  assign e_0 = e[0];

  assign e_1 = e[1];

  assign e_2 = e[2];

  assign e_3 = e[3];

  assign e_4 = e[4];

  assign e_5 = e[5];

  assign e_6 = e[6];

  assign e_7 = e[7];

  assign e_8 = e[8];

  assign e_9 = e[9];

  assign e_10 = e[10];

  assign e_11 = e[11];

  assign e_12 = e[12];

  assign e_13 = e[13];

  assign e_14 = e[14];

  assign e_15 = e[15];

  assign e_16 = e[16];

  assign e_17 = e[17];

  assign e_18 = e[18];

  assign e_19 = e[19];

  assign e_20 = e[20];

  assign e_21 = e[21];

  assign e_22 = e[22];

  assign e_23 = e[23];

  assign e_24 = e[24];

  assign e_25 = e[25];

  assign e_26 = e[26];

  assign e_27 = e[27];

  assign e_28 = e[28];

  assign e_29 = e[29];

  assign e_30 = e[30];

  assign e_31 = e[31];

  assign e_32 = e[32];

  assign e_33 = e[33];

  assign e_34 = e[34];

  assign e_35 = e[35];

  assign e_36 = e[36];

  assign e_37 = e[37];

  assign e_38 = e[38];

  assign e_39 = e[39];

  assign e_40 = e[40];

  assign e_41 = e[41];

  assign e_42 = e[42];

  assign e_43 = e[43];

  assign e_44 = e[44];

  assign e_45 = e[45];

  assign e_46 = e[46];

  assign e_47 = e[47];

  assign e_48 = e[48];

  assign e_49 = e[49];

  assign e_50 = e[50];

  assign e_51 = e[51];

  assign e_52 = e[52];

  assign e_53 = e[53];

  assign e_54 = e[54];

  assign e_55 = e[55];

  assign e_56 = e[56];

  assign e_57 = e[57];

  assign e_58 = e[58];

  assign e_59 = e[59];

  assign e_60 = e[60];

  assign e_61 = e[61];

  assign e_62 = e[62];

  assign e_63 = e[63];

  assign e_64 = e[64];

  assign e_65 = e[65];

  assign e_66 = e[66];

  assign e_67 = e[67];

  assign e_68 = e[68];

  assign e_69 = e[69];

  assign e_70 = e[70];

  assign e_71 = e[71];

  assign e_72 = e[72];

  assign e_73 = e[73];

  assign e_74 = e[74];

  assign e_75 = e[75];

  assign e_76 = e[76];

  assign e_77 = e[77];

  assign e_78 = e[78];

  assign e_79 = e[79];

  assign e_80 = e[80];

  assign e_81 = e[81];

  assign e_82 = e[82];

  assign e_83 = e[83];

  assign e_84 = e[84];

  assign e_85 = e[85];

  assign e_86 = e[86];

  assign e_87 = e[87];

  assign e_88 = e[88];

  assign e_89 = e[89];

  assign bhat_0 = bhat[0];

  assign bhat_1 = bhat[1];

  assign bhat_2 = bhat[2];

  assign bhat_3 = bhat[3];

  assign bhat_4 = bhat[4];

  assign bhat_5 = bhat[5];

  assign bhat_6 = bhat[6];

  assign bhat_7 = bhat[7];

  assign bhat_8 = bhat[8];

  assign bhat_9 = bhat[9];

  assign bhat_10 = bhat[10];

  assign bhat_11 = bhat[11];

  assign bhat_12 = bhat[12];

  assign bhat_13 = bhat[13];

  assign bhat_14 = bhat[14];

  assign bhat_15 = bhat[15];

  assign bhat_16 = bhat[16];

  assign bhat_17 = bhat[17];

  assign bhat_18 = bhat[18];

  assign bhat_19 = bhat[19];

  assign bhat_20 = bhat[20];

  assign bhat_21 = bhat[21];

  assign bhat_22 = bhat[22];

  assign bhat_23 = bhat[23];

  assign bhat_24 = bhat[24];

  assign bhat_25 = bhat[25];

  assign bhat_26 = bhat[26];

  assign bhat_27 = bhat[27];

  assign bhat_28 = bhat[28];

  assign bhat_29 = bhat[29];

  assign bhat_30 = bhat[30];

  assign bhat_31 = bhat[31];

  assign bhat_32 = bhat[32];

  assign bhat_33 = bhat[33];

  assign bhat_34 = bhat[34];

  assign bhat_35 = bhat[35];

  assign bhat_36 = bhat[36];

  assign bhat_37 = bhat[37];

  assign bhat_38 = bhat[38];

  assign bhat_39 = bhat[39];

  assign bhat_40 = bhat[40];

  assign bhat_41 = bhat[41];

  assign bhat_42 = bhat[42];

  assign bhat_43 = bhat[43];

  assign bhat_44 = bhat[44];

  assign bhat_45 = bhat[45];

  assign bhat_46 = bhat[46];

  assign bhat_47 = bhat[47];

  assign bhat_48 = bhat[48];

  assign bhat_49 = bhat[49];

  assign bhat_50 = bhat[50];

  assign bhat_51 = bhat[51];

  assign bhat_52 = bhat[52];

  assign bhat_53 = bhat[53];

  assign bhat_54 = bhat[54];

  assign bhat_55 = bhat[55];

  assign bhat_56 = bhat[56];

  assign bhat_57 = bhat[57];

  assign bhat_58 = bhat[58];

  assign bhat_59 = bhat[59];

  assign bhat_60 = bhat[60];

  assign bhat_61 = bhat[61];

  assign bhat_62 = bhat[62];

  assign bhat_63 = bhat[63];

  assign bhat_64 = bhat[64];

  assign bhat_65 = bhat[65];

  assign bhat_66 = bhat[66];

  assign bhat_67 = bhat[67];

  assign bhat_68 = bhat[68];

  assign bhat_69 = bhat[69];

  assign bhat_70 = bhat[70];

  assign bhat_71 = bhat[71];

  assign bhat_72 = bhat[72];

  assign bhat_73 = bhat[73];

  assign bhat_74 = bhat[74];

  assign bhat_75 = bhat[75];

  assign bhat_76 = bhat[76];

  assign bhat_77 = bhat[77];

  assign bhat_78 = bhat[78];

  assign bhat_79 = bhat[79];

  assign bhat_80 = bhat[80];

  assign bhat_81 = bhat[81];

  assign bhat_82 = bhat[82];

  assign bhat_83 = bhat[83];

  assign bhat_84 = bhat[84];

  assign bhat_85 = bhat[85];

  assign bhat_86 = bhat[86];

  assign bhat_87 = bhat[87];

  assign bhat_88 = bhat[88];

  assign bhat_89 = bhat[89];

  assign W = W_2;

endmodule  // noise_cancel_fixpt

