function noise_cancel_fixpt_programFPGA 
%noise_cancel_fixpt_programFPGA is a filWizard generated function used to load the
%   programming file for the 'noise_cancel_fixpt' HDL in the 'Nexys4 Artix-7 FPGA board' FPGA board. 
%
%   File Name: noise_cancel_fixpt_programFPGA.m
%   Created: 25-Apr-2017 20:39:57
% 
%   Generated by FIL Wizard

filProgramFPGA('Xilinx Vivado', ...
               'C:\Users\admin\Desktop\bhavesh\noise_cancel\fil\noise_cancel_fixpt_fil\noise_cancel_fixpt_fil.bit',...
               1);


end




