// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 8.1 and the Filter Design HDL Coder 2.9.3.
// Generated on: 2017-04-28 18:34:53
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// FIRAdderStyle: tree
// TargetDirectory: D:\FPGA\FDA_Filter
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Multipliers           : 51
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 51
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s20,20 -> [-5.000000e-01 5.000000e-01)
// Input             : s20,15 -> [-16 16)
// Filter Internals  : Full Precision
//   Output          : s42,35 -> [-64 64)  (auto determined)
//   Product         : s39,35 -> [-8 8)  (auto determined)
//   Accumulator     : s42,35 -> [-64 64)  (auto determined)
//   Round Mode      : No rounding
//   Overflow Mode   : No overflow
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module filter
               (
                input clk,
                input clk_enable,
                input reset,
                input [19:0] filter_in,
                output [41:0] filter_out
                );

 // input   clk; 
  //input   clk_enable; 
//  input   reset; 
 // input   signed [19:0] filter_in; //sfix20_En15
  //output  signed [41:0] filter_out; //sfix42_En35

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [19:0] coeff1 = 20'b11111111110000111100; //sfix20_En20
  parameter signed [19:0] coeff2 = 20'b11111111010011011110; //sfix20_En20
  parameter signed [19:0] coeff3 = 20'b11111111010111010000; //sfix20_En20
  parameter signed [19:0] coeff4 = 20'b00000000111011111111; //sfix20_En20
  parameter signed [19:0] coeff5 = 20'b00000011011111101010; //sfix20_En20
  parameter signed [19:0] coeff6 = 20'b00000100011100010010; //sfix20_En20
  parameter signed [19:0] coeff7 = 20'b00000001111101100110; //sfix20_En20
  parameter signed [19:0] coeff8 = 20'b11111110010100100111; //sfix20_En20
  parameter signed [19:0] coeff9 = 20'b11111110000001111001; //sfix20_En20
  parameter signed [19:0] coeff10 = 20'b00000001100100000010; //sfix20_En20
  parameter signed [19:0] coeff11 = 20'b00000011100011010100; //sfix20_En20
  parameter signed [19:0] coeff12 = 20'b00000000000101110000; //sfix20_En20
  parameter signed [19:0] coeff13 = 20'b11111011101010111110; //sfix20_En20
  parameter signed [19:0] coeff14 = 20'b11111101101110000110; //sfix20_En20
  parameter signed [19:0] coeff15 = 20'b00000100011101110000; //sfix20_En20
  parameter signed [19:0] coeff16 = 20'b00000101010011111001; //sfix20_En20
  parameter signed [19:0] coeff17 = 20'b11111100110110100010; //sfix20_En20
  parameter signed [19:0] coeff18 = 20'b11110111001111000000; //sfix20_En20
  parameter signed [19:0] coeff19 = 20'b11111111101111000011; //sfix20_En20
  parameter signed [19:0] coeff20 = 20'b00001100001111000000; //sfix20_En20
  parameter signed [19:0] coeff21 = 20'b00000111000000010100; //sfix20_En20
  parameter signed [19:0] coeff22 = 20'b11110000110011001000; //sfix20_En20
  parameter signed [19:0] coeff23 = 20'b11101010111011011111; //sfix20_En20
  parameter signed [19:0] coeff24 = 20'b00010001001100110011; //sfix20_En20
  parameter signed [19:0] coeff25 = 20'b01001111010111010010; //sfix20_En20
  parameter signed [19:0] coeff26 = 20'b01101110000101111010; //sfix20_En20
  parameter signed [19:0] coeff27 = 20'b01001111010111010010; //sfix20_En20
  parameter signed [19:0] coeff28 = 20'b00010001001100110011; //sfix20_En20
  parameter signed [19:0] coeff29 = 20'b11101010111011011111; //sfix20_En20
  parameter signed [19:0] coeff30 = 20'b11110000110011001000; //sfix20_En20
  parameter signed [19:0] coeff31 = 20'b00000111000000010100; //sfix20_En20
  parameter signed [19:0] coeff32 = 20'b00001100001111000000; //sfix20_En20
  parameter signed [19:0] coeff33 = 20'b11111111101111000011; //sfix20_En20
  parameter signed [19:0] coeff34 = 20'b11110111001111000000; //sfix20_En20
  parameter signed [19:0] coeff35 = 20'b11111100110110100010; //sfix20_En20
  parameter signed [19:0] coeff36 = 20'b00000101010011111001; //sfix20_En20
  parameter signed [19:0] coeff37 = 20'b00000100011101110000; //sfix20_En20
  parameter signed [19:0] coeff38 = 20'b11111101101110000110; //sfix20_En20
  parameter signed [19:0] coeff39 = 20'b11111011101010111110; //sfix20_En20
  parameter signed [19:0] coeff40 = 20'b00000000000101110000; //sfix20_En20
  parameter signed [19:0] coeff41 = 20'b00000011100011010100; //sfix20_En20
  parameter signed [19:0] coeff42 = 20'b00000001100100000010; //sfix20_En20
  parameter signed [19:0] coeff43 = 20'b11111110000001111001; //sfix20_En20
  parameter signed [19:0] coeff44 = 20'b11111110010100100111; //sfix20_En20
  parameter signed [19:0] coeff45 = 20'b00000001111101100110; //sfix20_En20
  parameter signed [19:0] coeff46 = 20'b00000100011100010010; //sfix20_En20
  parameter signed [19:0] coeff47 = 20'b00000011011111101010; //sfix20_En20
  parameter signed [19:0] coeff48 = 20'b00000000111011111111; //sfix20_En20
  parameter signed [19:0] coeff49 = 20'b11111111010111010000; //sfix20_En20
  parameter signed [19:0] coeff50 = 20'b11111111010011011110; //sfix20_En20
  parameter signed [19:0] coeff51 = 20'b11111111110000111100; //sfix20_En20

  // Signals

  reg  signed [19:0] delay_pipeline [0:50]; // sfix20_En15
  wire signed [38:0] product51; // sfix39_En35
  wire signed [39:0] mul_temp; // sfix40_En35
  wire signed [38:0] product50; // sfix39_En35
  wire signed [39:0] mul_temp_1; // sfix40_En35
  wire signed [38:0] product49; // sfix39_En35
  wire signed [39:0] mul_temp_2; // sfix40_En35
  wire signed [38:0] product48; // sfix39_En35
  wire signed [39:0] mul_temp_3; // sfix40_En35
  wire signed [38:0] product47; // sfix39_En35
  wire signed [39:0] mul_temp_4; // sfix40_En35
  wire signed [38:0] product46; // sfix39_En35
  wire signed [39:0] mul_temp_5; // sfix40_En35
  wire signed [38:0] product45; // sfix39_En35
  wire signed [39:0] mul_temp_6; // sfix40_En35
  wire signed [38:0] product44; // sfix39_En35
  wire signed [39:0] mul_temp_7; // sfix40_En35
  wire signed [38:0] product43; // sfix39_En35
  wire signed [39:0] mul_temp_8; // sfix40_En35
  wire signed [38:0] product42; // sfix39_En35
  wire signed [39:0] mul_temp_9; // sfix40_En35
  wire signed [38:0] product41; // sfix39_En35
  wire signed [39:0] mul_temp_10; // sfix40_En35
  wire signed [38:0] product40; // sfix39_En35
  wire signed [39:0] mul_temp_11; // sfix40_En35
  wire signed [38:0] product39; // sfix39_En35
  wire signed [39:0] mul_temp_12; // sfix40_En35
  wire signed [38:0] product38; // sfix39_En35
  wire signed [39:0] mul_temp_13; // sfix40_En35
  wire signed [38:0] product37; // sfix39_En35
  wire signed [39:0] mul_temp_14; // sfix40_En35
  wire signed [38:0] product36; // sfix39_En35
  wire signed [39:0] mul_temp_15; // sfix40_En35
  wire signed [38:0] product35; // sfix39_En35
  wire signed [39:0] mul_temp_16; // sfix40_En35
  wire signed [38:0] product34; // sfix39_En35
  wire signed [39:0] mul_temp_17; // sfix40_En35
  wire signed [38:0] product33; // sfix39_En35
  wire signed [39:0] mul_temp_18; // sfix40_En35
  wire signed [38:0] product32; // sfix39_En35
  wire signed [39:0] mul_temp_19; // sfix40_En35
  wire signed [38:0] product31; // sfix39_En35
  wire signed [39:0] mul_temp_20; // sfix40_En35
  wire signed [38:0] product30; // sfix39_En35
  wire signed [39:0] mul_temp_21; // sfix40_En35
  wire signed [38:0] product29; // sfix39_En35
  wire signed [39:0] mul_temp_22; // sfix40_En35
  wire signed [38:0] product28; // sfix39_En35
  wire signed [39:0] mul_temp_23; // sfix40_En35
  wire signed [38:0] product27; // sfix39_En35
  wire signed [39:0] mul_temp_24; // sfix40_En35
  wire signed [38:0] product26; // sfix39_En35
  wire signed [39:0] mul_temp_25; // sfix40_En35
  wire signed [38:0] product25; // sfix39_En35
  wire signed [39:0] mul_temp_26; // sfix40_En35
  wire signed [38:0] product24; // sfix39_En35
  wire signed [39:0] mul_temp_27; // sfix40_En35
  wire signed [38:0] product23; // sfix39_En35
  wire signed [39:0] mul_temp_28; // sfix40_En35
  wire signed [38:0] product22; // sfix39_En35
  wire signed [39:0] mul_temp_29; // sfix40_En35
  wire signed [38:0] product21; // sfix39_En35
  wire signed [39:0] mul_temp_30; // sfix40_En35
  wire signed [38:0] product20; // sfix39_En35
  wire signed [39:0] mul_temp_31; // sfix40_En35
  wire signed [38:0] product19; // sfix39_En35
  wire signed [39:0] mul_temp_32; // sfix40_En35
  wire signed [38:0] product18; // sfix39_En35
  wire signed [39:0] mul_temp_33; // sfix40_En35
  wire signed [38:0] product17; // sfix39_En35
  wire signed [39:0] mul_temp_34; // sfix40_En35
  wire signed [38:0] product16; // sfix39_En35
  wire signed [39:0] mul_temp_35; // sfix40_En35
  wire signed [38:0] product15; // sfix39_En35
  wire signed [39:0] mul_temp_36; // sfix40_En35
  wire signed [38:0] product14; // sfix39_En35
  wire signed [39:0] mul_temp_37; // sfix40_En35
  wire signed [38:0] product13; // sfix39_En35
  wire signed [39:0] mul_temp_38; // sfix40_En35
  wire signed [38:0] product12; // sfix39_En35
  wire signed [39:0] mul_temp_39; // sfix40_En35
  wire signed [38:0] product11; // sfix39_En35
  wire signed [39:0] mul_temp_40; // sfix40_En35
  wire signed [38:0] product10; // sfix39_En35
  wire signed [39:0] mul_temp_41; // sfix40_En35
  wire signed [38:0] product9; // sfix39_En35
  wire signed [39:0] mul_temp_42; // sfix40_En35
  wire signed [38:0] product8; // sfix39_En35
  wire signed [39:0] mul_temp_43; // sfix40_En35
  wire signed [38:0] product7; // sfix39_En35
  wire signed [39:0] mul_temp_44; // sfix40_En35
  wire signed [38:0] product6; // sfix39_En35
  wire signed [39:0] mul_temp_45; // sfix40_En35
  wire signed [38:0] product5; // sfix39_En35
  wire signed [39:0] mul_temp_46; // sfix40_En35
  wire signed [38:0] product4; // sfix39_En35
  wire signed [39:0] mul_temp_47; // sfix40_En35
  wire signed [38:0] product3; // sfix39_En35
  wire signed [39:0] mul_temp_48; // sfix40_En35
  wire signed [38:0] product2; // sfix39_En35
  wire signed [39:0] mul_temp_49; // sfix40_En35
  wire signed [38:0] product1; // sfix39_En35
  wire signed [39:0] mul_temp_50; // sfix40_En35
  wire signed [41:0] sum1_1; // sfix42_En35
  wire signed [38:0] add_signext; // sfix39_En35
  wire signed [38:0] add_signext_1; // sfix39_En35
  wire signed [39:0] add_temp; // sfix40_En35
  wire signed [41:0] sum1_2; // sfix42_En35
  wire signed [38:0] add_signext_2; // sfix39_En35
  wire signed [38:0] add_signext_3; // sfix39_En35
  wire signed [39:0] add_temp_1; // sfix40_En35
  wire signed [41:0] sum1_3; // sfix42_En35
  wire signed [38:0] add_signext_4; // sfix39_En35
  wire signed [38:0] add_signext_5; // sfix39_En35
  wire signed [39:0] add_temp_2; // sfix40_En35
  wire signed [41:0] sum1_4; // sfix42_En35
  wire signed [38:0] add_signext_6; // sfix39_En35
  wire signed [38:0] add_signext_7; // sfix39_En35
  wire signed [39:0] add_temp_3; // sfix40_En35
  wire signed [41:0] sum1_5; // sfix42_En35
  wire signed [38:0] add_signext_8; // sfix39_En35
  wire signed [38:0] add_signext_9; // sfix39_En35
  wire signed [39:0] add_temp_4; // sfix40_En35
  wire signed [41:0] sum1_6; // sfix42_En35
  wire signed [38:0] add_signext_10; // sfix39_En35
  wire signed [38:0] add_signext_11; // sfix39_En35
  wire signed [39:0] add_temp_5; // sfix40_En35
  wire signed [41:0] sum1_7; // sfix42_En35
  wire signed [38:0] add_signext_12; // sfix39_En35
  wire signed [38:0] add_signext_13; // sfix39_En35
  wire signed [39:0] add_temp_6; // sfix40_En35
  wire signed [41:0] sum1_8; // sfix42_En35
  wire signed [38:0] add_signext_14; // sfix39_En35
  wire signed [38:0] add_signext_15; // sfix39_En35
  wire signed [39:0] add_temp_7; // sfix40_En35
  wire signed [41:0] sum1_9; // sfix42_En35
  wire signed [38:0] add_signext_16; // sfix39_En35
  wire signed [38:0] add_signext_17; // sfix39_En35
  wire signed [39:0] add_temp_8; // sfix40_En35
  wire signed [41:0] sum1_10; // sfix42_En35
  wire signed [38:0] add_signext_18; // sfix39_En35
  wire signed [38:0] add_signext_19; // sfix39_En35
  wire signed [39:0] add_temp_9; // sfix40_En35
  wire signed [41:0] sum1_11; // sfix42_En35
  wire signed [38:0] add_signext_20; // sfix39_En35
  wire signed [38:0] add_signext_21; // sfix39_En35
  wire signed [39:0] add_temp_10; // sfix40_En35
  wire signed [41:0] sum1_12; // sfix42_En35
  wire signed [38:0] add_signext_22; // sfix39_En35
  wire signed [38:0] add_signext_23; // sfix39_En35
  wire signed [39:0] add_temp_11; // sfix40_En35
  wire signed [41:0] sum1_13; // sfix42_En35
  wire signed [38:0] add_signext_24; // sfix39_En35
  wire signed [38:0] add_signext_25; // sfix39_En35
  wire signed [39:0] add_temp_12; // sfix40_En35
  wire signed [41:0] sum1_14; // sfix42_En35
  wire signed [38:0] add_signext_26; // sfix39_En35
  wire signed [38:0] add_signext_27; // sfix39_En35
  wire signed [39:0] add_temp_13; // sfix40_En35
  wire signed [41:0] sum1_15; // sfix42_En35
  wire signed [38:0] add_signext_28; // sfix39_En35
  wire signed [38:0] add_signext_29; // sfix39_En35
  wire signed [39:0] add_temp_14; // sfix40_En35
  wire signed [41:0] sum1_16; // sfix42_En35
  wire signed [38:0] add_signext_30; // sfix39_En35
  wire signed [38:0] add_signext_31; // sfix39_En35
  wire signed [39:0] add_temp_15; // sfix40_En35
  wire signed [41:0] sum1_17; // sfix42_En35
  wire signed [38:0] add_signext_32; // sfix39_En35
  wire signed [38:0] add_signext_33; // sfix39_En35
  wire signed [39:0] add_temp_16; // sfix40_En35
  wire signed [41:0] sum1_18; // sfix42_En35
  wire signed [38:0] add_signext_34; // sfix39_En35
  wire signed [38:0] add_signext_35; // sfix39_En35
  wire signed [39:0] add_temp_17; // sfix40_En35
  wire signed [41:0] sum1_19; // sfix42_En35
  wire signed [38:0] add_signext_36; // sfix39_En35
  wire signed [38:0] add_signext_37; // sfix39_En35
  wire signed [39:0] add_temp_18; // sfix40_En35
  wire signed [41:0] sum1_20; // sfix42_En35
  wire signed [38:0] add_signext_38; // sfix39_En35
  wire signed [38:0] add_signext_39; // sfix39_En35
  wire signed [39:0] add_temp_19; // sfix40_En35
  wire signed [41:0] sum1_21; // sfix42_En35
  wire signed [38:0] add_signext_40; // sfix39_En35
  wire signed [38:0] add_signext_41; // sfix39_En35
  wire signed [39:0] add_temp_20; // sfix40_En35
  wire signed [41:0] sum1_22; // sfix42_En35
  wire signed [38:0] add_signext_42; // sfix39_En35
  wire signed [38:0] add_signext_43; // sfix39_En35
  wire signed [39:0] add_temp_21; // sfix40_En35
  wire signed [41:0] sum1_23; // sfix42_En35
  wire signed [38:0] add_signext_44; // sfix39_En35
  wire signed [38:0] add_signext_45; // sfix39_En35
  wire signed [39:0] add_temp_22; // sfix40_En35
  wire signed [41:0] sum1_24; // sfix42_En35
  wire signed [38:0] add_signext_46; // sfix39_En35
  wire signed [38:0] add_signext_47; // sfix39_En35
  wire signed [39:0] add_temp_23; // sfix40_En35
  wire signed [41:0] sum1_25; // sfix42_En35
  wire signed [38:0] add_signext_48; // sfix39_En35
  wire signed [38:0] add_signext_49; // sfix39_En35
  wire signed [39:0] add_temp_24; // sfix40_En35
  wire signed [41:0] sum2_1; // sfix42_En35
  wire signed [41:0] add_signext_50; // sfix42_En35
  wire signed [41:0] add_signext_51; // sfix42_En35
  wire signed [42:0] add_temp_25; // sfix43_En35
  wire signed [41:0] sum2_2; // sfix42_En35
  wire signed [41:0] add_signext_52; // sfix42_En35
  wire signed [41:0] add_signext_53; // sfix42_En35
  wire signed [42:0] add_temp_26; // sfix43_En35
  wire signed [41:0] sum2_3; // sfix42_En35
  wire signed [41:0] add_signext_54; // sfix42_En35
  wire signed [41:0] add_signext_55; // sfix42_En35
  wire signed [42:0] add_temp_27; // sfix43_En35
  wire signed [41:0] sum2_4; // sfix42_En35
  wire signed [41:0] add_signext_56; // sfix42_En35
  wire signed [41:0] add_signext_57; // sfix42_En35
  wire signed [42:0] add_temp_28; // sfix43_En35
  wire signed [41:0] sum2_5; // sfix42_En35
  wire signed [41:0] add_signext_58; // sfix42_En35
  wire signed [41:0] add_signext_59; // sfix42_En35
  wire signed [42:0] add_temp_29; // sfix43_En35
  wire signed [41:0] sum2_6; // sfix42_En35
  wire signed [41:0] add_signext_60; // sfix42_En35
  wire signed [41:0] add_signext_61; // sfix42_En35
  wire signed [42:0] add_temp_30; // sfix43_En35
  wire signed [41:0] sum2_7; // sfix42_En35
  wire signed [41:0] add_signext_62; // sfix42_En35
  wire signed [41:0] add_signext_63; // sfix42_En35
  wire signed [42:0] add_temp_31; // sfix43_En35
  wire signed [41:0] sum2_8; // sfix42_En35
  wire signed [41:0] add_signext_64; // sfix42_En35
  wire signed [41:0] add_signext_65; // sfix42_En35
  wire signed [42:0] add_temp_32; // sfix43_En35
  wire signed [41:0] sum2_9; // sfix42_En35
  wire signed [41:0] add_signext_66; // sfix42_En35
  wire signed [41:0] add_signext_67; // sfix42_En35
  wire signed [42:0] add_temp_33; // sfix43_En35
  wire signed [41:0] sum2_10; // sfix42_En35
  wire signed [41:0] add_signext_68; // sfix42_En35
  wire signed [41:0] add_signext_69; // sfix42_En35
  wire signed [42:0] add_temp_34; // sfix43_En35
  wire signed [41:0] sum2_11; // sfix42_En35
  wire signed [41:0] add_signext_70; // sfix42_En35
  wire signed [41:0] add_signext_71; // sfix42_En35
  wire signed [42:0] add_temp_35; // sfix43_En35
  wire signed [41:0] sum2_12; // sfix42_En35
  wire signed [41:0] add_signext_72; // sfix42_En35
  wire signed [41:0] add_signext_73; // sfix42_En35
  wire signed [42:0] add_temp_36; // sfix43_En35
  wire signed [41:0] sum2_13; // sfix42_En35
  wire signed [41:0] add_signext_74; // sfix42_En35
  wire signed [41:0] add_signext_75; // sfix42_En35
  wire signed [42:0] add_temp_37; // sfix43_En35
  wire signed [41:0] sum3_1; // sfix42_En35
  wire signed [41:0] add_signext_76; // sfix42_En35
  wire signed [41:0] add_signext_77; // sfix42_En35
  wire signed [42:0] add_temp_38; // sfix43_En35
  wire signed [41:0] sum3_2; // sfix42_En35
  wire signed [41:0] add_signext_78; // sfix42_En35
  wire signed [41:0] add_signext_79; // sfix42_En35
  wire signed [42:0] add_temp_39; // sfix43_En35
  wire signed [41:0] sum3_3; // sfix42_En35
  wire signed [41:0] add_signext_80; // sfix42_En35
  wire signed [41:0] add_signext_81; // sfix42_En35
  wire signed [42:0] add_temp_40; // sfix43_En35
  wire signed [41:0] sum3_4; // sfix42_En35
  wire signed [41:0] add_signext_82; // sfix42_En35
  wire signed [41:0] add_signext_83; // sfix42_En35
  wire signed [42:0] add_temp_41; // sfix43_En35
  wire signed [41:0] sum3_5; // sfix42_En35
  wire signed [41:0] add_signext_84; // sfix42_En35
  wire signed [41:0] add_signext_85; // sfix42_En35
  wire signed [42:0] add_temp_42; // sfix43_En35
  wire signed [41:0] sum3_6; // sfix42_En35
  wire signed [41:0] add_signext_86; // sfix42_En35
  wire signed [41:0] add_signext_87; // sfix42_En35
  wire signed [42:0] add_temp_43; // sfix43_En35
  wire signed [41:0] sum4_1; // sfix42_En35
  wire signed [41:0] add_signext_88; // sfix42_En35
  wire signed [41:0] add_signext_89; // sfix42_En35
  wire signed [42:0] add_temp_44; // sfix43_En35
  wire signed [41:0] sum4_2; // sfix42_En35
  wire signed [41:0] add_signext_90; // sfix42_En35
  wire signed [41:0] add_signext_91; // sfix42_En35
  wire signed [42:0] add_temp_45; // sfix43_En35
  wire signed [41:0] sum4_3; // sfix42_En35
  wire signed [41:0] add_signext_92; // sfix42_En35
  wire signed [41:0] add_signext_93; // sfix42_En35
  wire signed [42:0] add_temp_46; // sfix43_En35
  wire signed [41:0] sum5_1; // sfix42_En35
  wire signed [41:0] add_signext_94; // sfix42_En35
  wire signed [41:0] add_signext_95; // sfix42_En35
  wire signed [42:0] add_temp_47; // sfix43_En35
  wire signed [41:0] sum5_2; // sfix42_En35
  wire signed [41:0] add_signext_96; // sfix42_En35
  wire signed [41:0] add_signext_97; // sfix42_En35
  wire signed [42:0] add_temp_48; // sfix43_En35
  wire signed [41:0] sum6_1; // sfix42_En35
  wire signed [41:0] add_signext_98; // sfix42_En35
  wire signed [41:0] add_signext_99; // sfix42_En35
  wire signed [42:0] add_temp_49; // sfix43_En35
  reg  signed [41:0] output_register; // sfix42_En35

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
        delay_pipeline[33] <= 0;
        delay_pipeline[34] <= 0;
        delay_pipeline[35] <= 0;
        delay_pipeline[36] <= 0;
        delay_pipeline[37] <= 0;
        delay_pipeline[38] <= 0;
        delay_pipeline[39] <= 0;
        delay_pipeline[40] <= 0;
        delay_pipeline[41] <= 0;
        delay_pipeline[42] <= 0;
        delay_pipeline[43] <= 0;
        delay_pipeline[44] <= 0;
        delay_pipeline[45] <= 0;
        delay_pipeline[46] <= 0;
        delay_pipeline[47] <= 0;
        delay_pipeline[48] <= 0;
        delay_pipeline[49] <= 0;
        delay_pipeline[50] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
          delay_pipeline[33] <= delay_pipeline[32];
          delay_pipeline[34] <= delay_pipeline[33];
          delay_pipeline[35] <= delay_pipeline[34];
          delay_pipeline[36] <= delay_pipeline[35];
          delay_pipeline[37] <= delay_pipeline[36];
          delay_pipeline[38] <= delay_pipeline[37];
          delay_pipeline[39] <= delay_pipeline[38];
          delay_pipeline[40] <= delay_pipeline[39];
          delay_pipeline[41] <= delay_pipeline[40];
          delay_pipeline[42] <= delay_pipeline[41];
          delay_pipeline[43] <= delay_pipeline[42];
          delay_pipeline[44] <= delay_pipeline[43];
          delay_pipeline[45] <= delay_pipeline[44];
          delay_pipeline[46] <= delay_pipeline[45];
          delay_pipeline[47] <= delay_pipeline[46];
          delay_pipeline[48] <= delay_pipeline[47];
          delay_pipeline[49] <= delay_pipeline[48];
          delay_pipeline[50] <= delay_pipeline[49];
        end
      end
    end // Delay_Pipeline_process


  assign mul_temp = delay_pipeline[50] * coeff51;
  assign product51 = mul_temp[38:0];

  assign mul_temp_1 = delay_pipeline[49] * coeff50;
  assign product50 = mul_temp_1[38:0];

  assign mul_temp_2 = delay_pipeline[48] * coeff49;
  assign product49 = mul_temp_2[38:0];

  assign mul_temp_3 = delay_pipeline[47] * coeff48;
  assign product48 = mul_temp_3[38:0];

  assign mul_temp_4 = delay_pipeline[46] * coeff47;
  assign product47 = mul_temp_4[38:0];

  assign mul_temp_5 = delay_pipeline[45] * coeff46;
  assign product46 = mul_temp_5[38:0];

  assign mul_temp_6 = delay_pipeline[44] * coeff45;
  assign product45 = mul_temp_6[38:0];

  assign mul_temp_7 = delay_pipeline[43] * coeff44;
  assign product44 = mul_temp_7[38:0];

  assign mul_temp_8 = delay_pipeline[42] * coeff43;
  assign product43 = mul_temp_8[38:0];

  assign mul_temp_9 = delay_pipeline[41] * coeff42;
  assign product42 = mul_temp_9[38:0];

  assign mul_temp_10 = delay_pipeline[40] * coeff41;
  assign product41 = mul_temp_10[38:0];

  assign mul_temp_11 = delay_pipeline[39] * coeff40;
  assign product40 = mul_temp_11[38:0];

  assign mul_temp_12 = delay_pipeline[38] * coeff39;
  assign product39 = mul_temp_12[38:0];

  assign mul_temp_13 = delay_pipeline[37] * coeff38;
  assign product38 = mul_temp_13[38:0];

  assign mul_temp_14 = delay_pipeline[36] * coeff37;
  assign product37 = mul_temp_14[38:0];

  assign mul_temp_15 = delay_pipeline[35] * coeff36;
  assign product36 = mul_temp_15[38:0];

  assign mul_temp_16 = delay_pipeline[34] * coeff35;
  assign product35 = mul_temp_16[38:0];

  assign mul_temp_17 = delay_pipeline[33] * coeff34;
  assign product34 = mul_temp_17[38:0];

  assign mul_temp_18 = delay_pipeline[32] * coeff33;
  assign product33 = mul_temp_18[38:0];

  assign mul_temp_19 = delay_pipeline[31] * coeff32;
  assign product32 = mul_temp_19[38:0];

  assign mul_temp_20 = delay_pipeline[30] * coeff31;
  assign product31 = mul_temp_20[38:0];

  assign mul_temp_21 = delay_pipeline[29] * coeff30;
  assign product30 = mul_temp_21[38:0];

  assign mul_temp_22 = delay_pipeline[28] * coeff29;
  assign product29 = mul_temp_22[38:0];

  assign mul_temp_23 = delay_pipeline[27] * coeff28;
  assign product28 = mul_temp_23[38:0];

  assign mul_temp_24 = delay_pipeline[26] * coeff27;
  assign product27 = mul_temp_24[38:0];

  assign mul_temp_25 = delay_pipeline[25] * coeff26;
  assign product26 = mul_temp_25[38:0];

  assign mul_temp_26 = delay_pipeline[24] * coeff25;
  assign product25 = mul_temp_26[38:0];

  assign mul_temp_27 = delay_pipeline[23] * coeff24;
  assign product24 = mul_temp_27[38:0];

  assign mul_temp_28 = delay_pipeline[22] * coeff23;
  assign product23 = mul_temp_28[38:0];

  assign mul_temp_29 = delay_pipeline[21] * coeff22;
  assign product22 = mul_temp_29[38:0];

  assign mul_temp_30 = delay_pipeline[20] * coeff21;
  assign product21 = mul_temp_30[38:0];

  assign mul_temp_31 = delay_pipeline[19] * coeff20;
  assign product20 = mul_temp_31[38:0];

  assign mul_temp_32 = delay_pipeline[18] * coeff19;
  assign product19 = mul_temp_32[38:0];

  assign mul_temp_33 = delay_pipeline[17] * coeff18;
  assign product18 = mul_temp_33[38:0];

  assign mul_temp_34 = delay_pipeline[16] * coeff17;
  assign product17 = mul_temp_34[38:0];

  assign mul_temp_35 = delay_pipeline[15] * coeff16;
  assign product16 = mul_temp_35[38:0];

  assign mul_temp_36 = delay_pipeline[14] * coeff15;
  assign product15 = mul_temp_36[38:0];

  assign mul_temp_37 = delay_pipeline[13] * coeff14;
  assign product14 = mul_temp_37[38:0];

  assign mul_temp_38 = delay_pipeline[12] * coeff13;
  assign product13 = mul_temp_38[38:0];

  assign mul_temp_39 = delay_pipeline[11] * coeff12;
  assign product12 = mul_temp_39[38:0];

  assign mul_temp_40 = delay_pipeline[10] * coeff11;
  assign product11 = mul_temp_40[38:0];

  assign mul_temp_41 = delay_pipeline[9] * coeff10;
  assign product10 = mul_temp_41[38:0];

  assign mul_temp_42 = delay_pipeline[8] * coeff9;
  assign product9 = mul_temp_42[38:0];

  assign mul_temp_43 = delay_pipeline[7] * coeff8;
  assign product8 = mul_temp_43[38:0];

  assign mul_temp_44 = delay_pipeline[6] * coeff7;
  assign product7 = mul_temp_44[38:0];

  assign mul_temp_45 = delay_pipeline[5] * coeff6;
  assign product6 = mul_temp_45[38:0];

  assign mul_temp_46 = delay_pipeline[4] * coeff5;
  assign product5 = mul_temp_46[38:0];

  assign mul_temp_47 = delay_pipeline[3] * coeff4;
  assign product4 = mul_temp_47[38:0];

  assign mul_temp_48 = delay_pipeline[2] * coeff3;
  assign product3 = mul_temp_48[38:0];

  assign mul_temp_49 = delay_pipeline[1] * coeff2;
  assign product2 = mul_temp_49[38:0];

  assign mul_temp_50 = delay_pipeline[0] * coeff1;
  assign product1 = mul_temp_50[38:0];

  assign add_signext = product51;
  assign add_signext_1 = product50;
  assign add_temp = add_signext + add_signext_1;
  assign sum1_1 = $signed({{2{add_temp[39]}}, add_temp});

  assign add_signext_2 = product49;
  assign add_signext_3 = product48;
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum1_2 = $signed({{2{add_temp_1[39]}}, add_temp_1});

  assign add_signext_4 = product47;
  assign add_signext_5 = product46;
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum1_3 = $signed({{2{add_temp_2[39]}}, add_temp_2});

  assign add_signext_6 = product45;
  assign add_signext_7 = product44;
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum1_4 = $signed({{2{add_temp_3[39]}}, add_temp_3});

  assign add_signext_8 = product43;
  assign add_signext_9 = product42;
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum1_5 = $signed({{2{add_temp_4[39]}}, add_temp_4});

  assign add_signext_10 = product41;
  assign add_signext_11 = product40;
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum1_6 = $signed({{2{add_temp_5[39]}}, add_temp_5});

  assign add_signext_12 = product39;
  assign add_signext_13 = product38;
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum1_7 = $signed({{2{add_temp_6[39]}}, add_temp_6});

  assign add_signext_14 = product37;
  assign add_signext_15 = product36;
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum1_8 = $signed({{2{add_temp_7[39]}}, add_temp_7});

  assign add_signext_16 = product35;
  assign add_signext_17 = product34;
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum1_9 = $signed({{2{add_temp_8[39]}}, add_temp_8});

  assign add_signext_18 = product33;
  assign add_signext_19 = product32;
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum1_10 = $signed({{2{add_temp_9[39]}}, add_temp_9});

  assign add_signext_20 = product31;
  assign add_signext_21 = product30;
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum1_11 = $signed({{2{add_temp_10[39]}}, add_temp_10});

  assign add_signext_22 = product29;
  assign add_signext_23 = product28;
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum1_12 = $signed({{2{add_temp_11[39]}}, add_temp_11});

  assign add_signext_24 = product27;
  assign add_signext_25 = product26;
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum1_13 = $signed({{2{add_temp_12[39]}}, add_temp_12});

  assign add_signext_26 = product25;
  assign add_signext_27 = product24;
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum1_14 = $signed({{2{add_temp_13[39]}}, add_temp_13});

  assign add_signext_28 = product23;
  assign add_signext_29 = product22;
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum1_15 = $signed({{2{add_temp_14[39]}}, add_temp_14});

  assign add_signext_30 = product21;
  assign add_signext_31 = product20;
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum1_16 = $signed({{2{add_temp_15[39]}}, add_temp_15});

  assign add_signext_32 = product19;
  assign add_signext_33 = product18;
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum1_17 = $signed({{2{add_temp_16[39]}}, add_temp_16});

  assign add_signext_34 = product17;
  assign add_signext_35 = product16;
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum1_18 = $signed({{2{add_temp_17[39]}}, add_temp_17});

  assign add_signext_36 = product15;
  assign add_signext_37 = product14;
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum1_19 = $signed({{2{add_temp_18[39]}}, add_temp_18});

  assign add_signext_38 = product13;
  assign add_signext_39 = product12;
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum1_20 = $signed({{2{add_temp_19[39]}}, add_temp_19});

  assign add_signext_40 = product11;
  assign add_signext_41 = product10;
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum1_21 = $signed({{2{add_temp_20[39]}}, add_temp_20});

  assign add_signext_42 = product9;
  assign add_signext_43 = product8;
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum1_22 = $signed({{2{add_temp_21[39]}}, add_temp_21});

  assign add_signext_44 = product7;
  assign add_signext_45 = product6;
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum1_23 = $signed({{2{add_temp_22[39]}}, add_temp_22});

  assign add_signext_46 = product5;
  assign add_signext_47 = product4;
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum1_24 = $signed({{2{add_temp_23[39]}}, add_temp_23});

  assign add_signext_48 = product3;
  assign add_signext_49 = product2;
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum1_25 = $signed({{2{add_temp_24[39]}}, add_temp_24});

  assign add_signext_50 = sum1_1;
  assign add_signext_51 = sum1_2;
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum2_1 = add_temp_25[41:0];

  assign add_signext_52 = sum1_3;
  assign add_signext_53 = sum1_4;
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum2_2 = add_temp_26[41:0];

  assign add_signext_54 = sum1_5;
  assign add_signext_55 = sum1_6;
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum2_3 = add_temp_27[41:0];

  assign add_signext_56 = sum1_7;
  assign add_signext_57 = sum1_8;
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum2_4 = add_temp_28[41:0];

  assign add_signext_58 = sum1_9;
  assign add_signext_59 = sum1_10;
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum2_5 = add_temp_29[41:0];

  assign add_signext_60 = sum1_11;
  assign add_signext_61 = sum1_12;
  assign add_temp_30 = add_signext_60 + add_signext_61;
  assign sum2_6 = add_temp_30[41:0];

  assign add_signext_62 = sum1_13;
  assign add_signext_63 = sum1_14;
  assign add_temp_31 = add_signext_62 + add_signext_63;
  assign sum2_7 = add_temp_31[41:0];

  assign add_signext_64 = sum1_15;
  assign add_signext_65 = sum1_16;
  assign add_temp_32 = add_signext_64 + add_signext_65;
  assign sum2_8 = add_temp_32[41:0];

  assign add_signext_66 = sum1_17;
  assign add_signext_67 = sum1_18;
  assign add_temp_33 = add_signext_66 + add_signext_67;
  assign sum2_9 = add_temp_33[41:0];

  assign add_signext_68 = sum1_19;
  assign add_signext_69 = sum1_20;
  assign add_temp_34 = add_signext_68 + add_signext_69;
  assign sum2_10 = add_temp_34[41:0];

  assign add_signext_70 = sum1_21;
  assign add_signext_71 = sum1_22;
  assign add_temp_35 = add_signext_70 + add_signext_71;
  assign sum2_11 = add_temp_35[41:0];

  assign add_signext_72 = sum1_23;
  assign add_signext_73 = sum1_24;
  assign add_temp_36 = add_signext_72 + add_signext_73;
  assign sum2_12 = add_temp_36[41:0];

  assign add_signext_74 = sum1_25;
  assign add_signext_75 = $signed({{3{product1[38]}}, product1});
  assign add_temp_37 = add_signext_74 + add_signext_75;
  assign sum2_13 = add_temp_37[41:0];

  assign add_signext_76 = sum2_1;
  assign add_signext_77 = sum2_2;
  assign add_temp_38 = add_signext_76 + add_signext_77;
  assign sum3_1 = add_temp_38[41:0];

  assign add_signext_78 = sum2_3;
  assign add_signext_79 = sum2_4;
  assign add_temp_39 = add_signext_78 + add_signext_79;
  assign sum3_2 = add_temp_39[41:0];

  assign add_signext_80 = sum2_5;
  assign add_signext_81 = sum2_6;
  assign add_temp_40 = add_signext_80 + add_signext_81;
  assign sum3_3 = add_temp_40[41:0];

  assign add_signext_82 = sum2_7;
  assign add_signext_83 = sum2_8;
  assign add_temp_41 = add_signext_82 + add_signext_83;
  assign sum3_4 = add_temp_41[41:0];

  assign add_signext_84 = sum2_9;
  assign add_signext_85 = sum2_10;
  assign add_temp_42 = add_signext_84 + add_signext_85;
  assign sum3_5 = add_temp_42[41:0];

  assign add_signext_86 = sum2_11;
  assign add_signext_87 = sum2_12;
  assign add_temp_43 = add_signext_86 + add_signext_87;
  assign sum3_6 = add_temp_43[41:0];

  assign add_signext_88 = sum3_1;
  assign add_signext_89 = sum3_2;
  assign add_temp_44 = add_signext_88 + add_signext_89;
  assign sum4_1 = add_temp_44[41:0];

  assign add_signext_90 = sum3_3;
  assign add_signext_91 = sum3_4;
  assign add_temp_45 = add_signext_90 + add_signext_91;
  assign sum4_2 = add_temp_45[41:0];

  assign add_signext_92 = sum3_5;
  assign add_signext_93 = sum3_6;
  assign add_temp_46 = add_signext_92 + add_signext_93;
  assign sum4_3 = add_temp_46[41:0];

  assign add_signext_94 = sum4_1;
  assign add_signext_95 = sum4_2;
  assign add_temp_47 = add_signext_94 + add_signext_95;
  assign sum5_1 = add_temp_47[41:0];

  assign add_signext_96 = sum4_3;
  assign add_signext_97 = sum2_13;
  assign add_temp_48 = add_signext_96 + add_signext_97;
  assign sum5_2 = add_temp_48[41:0];

  assign add_signext_98 = sum5_1;
  assign add_signext_99 = sum5_2;
  assign add_temp_49 = add_signext_98 + add_signext_99;
  assign sum6_1 = add_temp_49[41:0];

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= sum6_1;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
