% Function localRecompile_noise_cancel_wrapper_fixpt_fil recreates a MEX-function noise_cancel_wrapper_fixpt_fil_mex from MATLAB function noise_cancel_wrapper_fixpt_fil
% Generated by MATLAB 9.2 and HDL Coder 3.10
function localRecompile_noise_cancel_wrapper_fixpt_fil

load('C:\Users\admin\Desktop\bhavesh\noise_cancel\fil\localCodegenArgs_noise_cancel_wrapper_fixpt_fil');

fxptPath = 'C:\Users\admin\Desktop\bhavesh\noise_cancel\fixpt';
addpath(fxptPath);
cleanupObj = onCleanup(@() rmpath(fxptPath));
codegen -args exInputs -o 'C:\Users\admin\Desktop\bhavesh\noise_cancel\fil\noise_cancel_wrapper_fixpt_fil_mex' noise_cancel_wrapper_fixpt_fil;

