% Auto generated function to simulate the generated HDL code using FPGA-in-the-Loop
% 
% Generated by MATLAB 9.2 and HDL Coder 3.10

function [ref_e,ref_W,ref_bhat] = noise_cancel_fixpt_fil(s,n)

coder.extrinsic('noise_cancel_fixpt_sysobj_fil');
coder.extrinsic('hdlverifier.assert');
coder.extrinsic('hdlverifier.Delay');
coder.extrinsic('step');

% Declare persistent variables
persistent initialized;

% Initialize persistent variables
if isempty(initialized)
   initialized = true;
end

% Call the original MATLAB function to get reference signal
[ref_e,ref_W,ref_bhat] = noise_cancel_fixpt(s,n);

% Convert input signals
s_1 = s(1);

s_2 = s(2);

s_3 = s(3);

s_4 = s(4);

s_5 = s(5);

s_6 = s(6);

s_7 = s(7);

s_8 = s(8);

s_9 = s(9);

s_10 = s(10);

s_11 = s(11);

s_12 = s(12);

s_13 = s(13);

s_14 = s(14);

s_15 = s(15);

s_16 = s(16);

s_17 = s(17);

s_18 = s(18);

s_19 = s(19);

s_20 = s(20);

s_21 = s(21);

s_22 = s(22);

s_23 = s(23);

s_24 = s(24);

s_25 = s(25);

s_26 = s(26);

s_27 = s(27);

s_28 = s(28);

s_29 = s(29);

s_30 = s(30);

s_31 = s(31);

s_32 = s(32);

s_33 = s(33);

s_34 = s(34);

s_35 = s(35);

s_36 = s(36);

s_37 = s(37);

s_38 = s(38);

s_39 = s(39);

s_40 = s(40);

s_41 = s(41);

s_42 = s(42);

s_43 = s(43);

s_44 = s(44);

s_45 = s(45);

s_46 = s(46);

s_47 = s(47);

s_48 = s(48);

s_49 = s(49);

s_50 = s(50);

s_51 = s(51);

s_52 = s(52);

s_53 = s(53);

s_54 = s(54);

s_55 = s(55);

s_56 = s(56);

s_57 = s(57);

s_58 = s(58);

s_59 = s(59);

s_60 = s(60);

s_61 = s(61);

s_62 = s(62);

s_63 = s(63);

s_64 = s(64);

s_65 = s(65);

s_66 = s(66);

s_67 = s(67);

s_68 = s(68);

s_69 = s(69);

s_70 = s(70);

s_71 = s(71);

s_72 = s(72);

s_73 = s(73);

s_74 = s(74);

s_75 = s(75);

s_76 = s(76);

s_77 = s(77);

s_78 = s(78);

s_79 = s(79);

s_80 = s(80);

s_81 = s(81);

s_82 = s(82);

s_83 = s(83);

s_84 = s(84);

s_85 = s(85);

s_86 = s(86);

s_87 = s(87);

s_88 = s(88);

s_89 = s(89);

s_90 = s(90);

s_91 = s(91);

s_92 = s(92);

s_93 = s(93);

s_94 = s(94);

s_95 = s(95);

s_96 = s(96);

s_97 = s(97);

s_98 = s(98);

s_99 = s(99);

s_100 = s(100);

n_1 = n(1);

n_2 = n(2);

n_3 = n(3);

n_4 = n(4);

n_5 = n(5);

n_6 = n(6);

n_7 = n(7);

n_8 = n(8);

n_9 = n(9);

n_10 = n(10);

n_11 = n(11);

n_12 = n(12);

n_13 = n(13);

n_14 = n(14);

n_15 = n(15);

n_16 = n(16);

n_17 = n(17);

n_18 = n(18);

n_19 = n(19);

n_20 = n(20);

n_21 = n(21);

n_22 = n(22);

n_23 = n(23);

n_24 = n(24);

n_25 = n(25);

n_26 = n(26);

n_27 = n(27);

n_28 = n(28);

n_29 = n(29);

n_30 = n(30);

n_31 = n(31);

n_32 = n(32);

n_33 = n(33);

n_34 = n(34);

n_35 = n(35);

n_36 = n(36);

n_37 = n(37);

n_38 = n(38);

n_39 = n(39);

n_40 = n(40);

n_41 = n(41);

n_42 = n(42);

n_43 = n(43);

n_44 = n(44);

n_45 = n(45);

n_46 = n(46);

n_47 = n(47);

n_48 = n(48);

n_49 = n(49);

n_50 = n(50);

n_51 = n(51);

n_52 = n(52);

n_53 = n(53);

n_54 = n(54);

n_55 = n(55);

n_56 = n(56);

n_57 = n(57);

n_58 = n(58);

n_59 = n(59);

n_60 = n(60);

n_61 = n(61);

n_62 = n(62);

n_63 = n(63);

n_64 = n(64);

n_65 = n(65);

n_66 = n(66);

n_67 = n(67);

n_68 = n(68);

n_69 = n(69);

n_70 = n(70);

n_71 = n(71);

n_72 = n(72);

n_73 = n(73);

n_74 = n(74);

n_75 = n(75);

n_76 = n(76);

n_77 = n(77);

n_78 = n(78);

n_79 = n(79);

n_80 = n(80);

n_81 = n(81);

n_82 = n(82);

n_83 = n(83);

n_84 = n(84);

n_85 = n(85);

n_86 = n(86);

n_87 = n(87);

n_88 = n(88);

n_89 = n(89);

n_90 = n(90);

n_91 = n(91);

n_92 = n(92);

n_93 = n(93);

n_94 = n(94);

n_95 = n(95);

n_96 = n(96);

n_97 = n(97);

n_98 = n(98);

n_99 = n(99);

n_100 = n(100);



% Run FPGA-in-the-Loop
[e_1,e_2,e_3,e_4,e_5,e_6,e_7,e_8,e_9,e_10,e_11,e_12,e_13,e_14,e_15,e_16,e_17,e_18,e_19,e_20,e_21,e_22,e_23,e_24,e_25,e_26,W,bhat_1,bhat_2,bhat_3,bhat_4,bhat_5,bhat_6,bhat_7,bhat_8,bhat_9,bhat_10,bhat_11,bhat_12,bhat_13,bhat_14,bhat_15,bhat_16,bhat_17,bhat_18,bhat_19,bhat_20,bhat_21,bhat_22,bhat_23,bhat_24,bhat_25,bhat_26] = noise_cancel_fixpt_sysobj_fil(s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10,s_11,s_12,s_13,s_14,s_15,s_16,s_17,s_18,s_19,s_20,s_21,s_22,s_23,s_24,s_25,s_26,s_27,s_28,s_29,s_30,s_31,s_32,s_33,s_34,s_35,s_36,s_37,s_38,s_39,s_40,s_41,s_42,s_43,s_44,s_45,s_46,s_47,s_48,s_49,s_50,s_51,s_52,s_53,s_54,s_55,s_56,s_57,s_58,s_59,s_60,s_61,s_62,s_63,s_64,s_65,s_66,s_67,s_68,s_69,s_70,s_71,s_72,s_73,s_74,s_75,s_76,s_77,s_78,s_79,s_80,s_81,s_82,s_83,s_84,s_85,s_86,s_87,s_88,s_89,s_90,s_91,s_92,s_93,s_94,s_95,s_96,s_97,s_98,s_99,s_100,n_1,n_2,n_3,n_4,n_5,n_6,n_7,n_8,n_9,n_10,n_11,n_12,n_13,n_14,n_15,n_16,n_17,n_18,n_19,n_20,n_21,n_22,n_23,n_24,n_25,n_26,n_27,n_28,n_29,n_30,n_31,n_32,n_33,n_34,n_35,n_36,n_37,n_38,n_39,n_40,n_41,n_42,n_43,n_44,n_45,n_46,n_47,n_48,n_49,n_50,n_51,n_52,n_53,n_54,n_55,n_56,n_57,n_58,n_59,n_60,n_61,n_62,n_63,n_64,n_65,n_66,n_67,n_68,n_69,n_70,n_71,n_72,n_73,n_74,n_75,n_76,n_77,n_78,n_79,n_80,n_81,n_82,n_83,n_84,n_85,n_86,n_87,n_88,n_89,n_90,n_91,n_92,n_93,n_94,n_95,n_96,n_97,n_98,n_99,n_100);

% Convert output signals
bhat = [bhat_1,bhat_2,bhat_3,bhat_4,bhat_5,bhat_6,bhat_7,bhat_8,bhat_9,bhat_10,bhat_11,bhat_12,bhat_13,bhat_14,bhat_15,bhat_16,bhat_17,bhat_18,bhat_19,bhat_20,bhat_21,bhat_22,bhat_23,bhat_24,bhat_25,bhat_26];

e = [e_1,e_2,e_3,e_4,e_5,e_6,e_7,e_8,e_9,e_10,e_11,e_12,e_13,e_14,e_15,e_16,e_17,e_18,e_19,e_20,e_21,e_22,e_23,e_24,e_25,e_26];



% Verify the FPGA-in-the-Loop output
hdlverifier.assert(e,ref_e,'e');
hdlverifier.assert(W,ref_W,'W');
hdlverifier.assert(bhat,ref_bhat,'bhat');

coder.extrinsic('localLogData');
localLogData(e,W,bhat,ref_e,ref_W,ref_bhat);
